### PR TITLE
Patch to develop command line script

### PR DESCRIPTION
**Pull request by brtietz**
Update develop with the new Travis tests.

- Windows has been tested
- Opening the PR will check the expected results on Travis
- @dguittet Can you test the Mac build?
- I'll test the Linux builds

### CODE REVIEW

**Comment by brtietz** [comment]
Travis build passing (https://travis-ci.org/github/NREL/SAM/builds/692685564) current build is running with updated Linux results.

I was able to successfully build on Linux with both separate projects and all in one.

**Comment by dguittet** [comment]
SAM built separately and as single project.

I changed the paths in the travis script to reflect MacOS paths, and the `cut` command since the utility is a bit different on mac. Was able to run the full command minus the `Xvfb` part with expected behavior.

If you are intending to test on Mac in Travis, consider adding to .travis.yml as in ssc:

```
os:
  - linux
  - osx
```

**Comment by brtietz** [comment]
Thanks for the review and the path fixes. I merged this in, since the change to travis.yml to test osx should also go to patch.

**Comment by brtietz** [comment]
Looks like getting osx to work for that build is a major job: https://travis-ci.org/github/NREL/SAM/jobs/693567731

I'll bring up whether or not we want to do it for discussion at this week's SAM meeting.

**Pull request closed without merging**
