### PR TITLE
New Operating Costs input page

### PR DESCRIPTION
**Pull request by cpaulgilman**
This PR is a prerequisite for fixing #355 (see also related https://github.com/NREL/ssc/pull/530) and adding new inputs for Community Solar financial model. Changes include:

* Separate Installation Costs and Operating Costs input pages

* UI forms for operating costs, operating costs with fuel, battery, and fuel cell.

* Update defaults for operating cost inputs.

* Remove unused battery-related operating cost inputs from PVWatts Battery configurations.

* New structure for Help topics on costs.

### CODE REVIEW

**Comment by mjprilliman** [comment]
image

image

I think you need some text for these new section header pages in the Help Paul.

**Comment by mjprilliman** [comment]
image

I would like to propose something like this for the marine models to be consistent. Those changes may be in a separate PR down the road.

**Comment by mjprilliman** [comment]
image

Do you want wave, tidal, and concentrating PV costs to be in this menu or leave them in the existing technology menus?

**Comment by mjprilliman** [comment]
image

Typo

**Review by mjprilliman — APPROVED** [review]
See comments above.

**Comment by sjanzou** [comment]
Running all defaults on Windows fails with MEwave / LCOW calculator:
image

**Review by sjanzou — APPROVED** [review]
I think with the $/kWh battery replacement costs discussed at the 7/13/21 SAM meeting and if the failing UI with MEwave / LCOE calculator is fixed (see comments) and all tests passing, that this should be ready to go and getting merged into develop before community solar is great! Thanks for tackling this!

**Comment by mjprilliman** [comment]
> I think with the $/kWh battery replacement costs discussed at the 7/13/21 SAM meeting and if the failing UI with MEwave / LCOE calculator is fixed (see comments) and all tests passing, that this should be ready to go and getting merged into develop before community solar is great! Thanks for tackling this!

I'm pretty sure the MEwave defaults issue is a quirk with the library building. On load the case config is looking at the existing local app data for the WaveResourceData.csv file, which has different variable names that have since been changed in the IDE library object and library setup scripts. Clicking 'Refresh library' should rewrite the library and fix the issue. I didn't find a way to update this automatically as the check happens before the pages load so it would be a more complicated fix. The hope is that this is going into a new release version so the local app data would be brand new and not looking at any existing WaveResourceData.csv files on first load.

**Comment by cpaulgilman** [comment]
I'm not seeing the message about 'file_name', and given Matt's comments will go ahead with the merge.

**Pull request merged**
