### PR TITLE
Updated loss factor adjustments widget for lifetime, subhourly

### LINKED ISSUE #703: Loss Adjustment improvements
### Overview

The LossAdjustment widget is currently designed to read loss inputs over one year as percentages in a combination of 1) a constant percentage, 2) array of hourly percentages, and/or 3) array of [start hour, end hour, percentage] arrays. This makes it unsuitable to use for a the new `grid_outage` input, which is a lifetime time series array of 0/1 values, or for other time series inputs such as curtailment that are not percentages and may be subhourly.

The widget is currently used as a "system availability" input for some models: CSP System Design or Power Cycle input pages, Detailed PV Losses page for DC and AC availability, etc. Note that Wind uses the DataArray widget to support subhourly values. See below for a list of all UI forms that use the widget.

loss-adjustment

### Adjustment Factors Class in SSC

The `adjustment_factors` class defined in common.cpp converts the percentage values to factors, and calculates a total loss factor for each hour from the three inputs, returning an 8760 array of factors. 

The widget is used on the UI forms listed below for the `adjust`, `sf_adjust`, and `dc_adjust` inputs to SSC compute modules. Search the Visual Studio SAM project for "adjustment_factors" to find all instances of the class in SSC.

### Suggested Modifications

1. Support for lifetime and subhourly arrays: Could be implemented by using DataLifetimeArray instead of DataArray for the current "Enable hourly values" option.

2. Return an array of values instead of a table of percentages. This would allow the widget to be used for any lifetime time series input with hourly or subhourly time steps.

3. Add Description and Label properties.

### Considerations

If the widget returns an array of values, then the `adjustment_factors` class would no longer be needed to handle the special table format and the conversion from percentages to factors. Making this change would require updating all `adjust`, `sf_adjust`, and `dc_adjust` variables SSC.

This change would break code written by SDK or PySAM users that uses those variables. This could be handled by writing a function to detect and convert those variables.

An alternative would be to keep the current widget and SSC class, and to create a new widget for "time series values with custom periods" that converts a set of [ start time step, stop time step, value ] arrays to a lifetime array. Then, options for entering lifetime inputs could be handled in the UI, for example, three inputs for Constant, Time Series, Custom Periods would be defined as separate widgets in the UI and a UI equation would process those inputs into a single time series array.

### List of UI Forms Using the LossAdjustment Widget

```
form object: Biopower Plant Specifications.object{adjust} = LossAdjustment
form object: Dish Solar Field.object{adjust} = LossAdjustment
form object: Empirical Trough Power Block.object{adjust} = LossAdjustment
form object: Generic CSP Power Block.object{adjust} = LossAdjustment
form object: Generic CSP Solar Field.object{sf_adjust} = LossAdjustment
form object: Generic System Plant.object{adjust} = LossAdjustment
form object: Geothermal Plant and Equipment.object{adjust} = LossAdjustment
form object: Grid Outage.object{} = LossAdjustment
form object: HCPV Array.object{adjust} = LossAdjustment
form object: ISCC Receiver and Powerblock.object{adjust} = LossAdjustment
form object: LF DSG System Design.object{adjust} = LossAdjustment
form object: Molten Salt Linear Fresnel Power Cycle.object{adjust} = LossAdjustment
form object: MSLF Power Cycle Common.object{adjust} = LossAdjustment
form object: MSPT System Control.object{adjust} = LossAdjustment
form object: PBNS Power Block.object{adjust} = LossAdjustment
form object: Phys Trough System Control.object{adjust} = LossAdjustment
form object: Physical Trough Power Block Common.object{adjust} = LossAdjustment
form object: Physical Trough Power Block.object{adjust} = LossAdjustment
form object: Physical Trough System Control.object{adjust} = LossAdjustment
form object: PV Losses.object{adjust} = LossAdjustment
form object: PV Losses.object{dc_adjust} = LossAdjustment
form object: PV2 Interconnection.object{adjust} = LossAdjustment
form object: PVWatts.object{adjust} = LossAdjustment
form object: Solar Water Heating.object{adjust} = LossAdjustment
form object: Tower Solar Field.object{sf_adjust} = LossAdjustment
form object: Tower SolarPilot Solar Field.object{sf_adjust} = LossAdjustment
```

### PR DESCRIPTION
**Pull request by mjprilliman**
## Description

-Add Lifetime data array to loss adjustment widget to allow for lifetime, subhourly loss specifications
-Turn percentage inputs to fraction inputs (0-1)
-Have analysis_period for lifetime array widget automatically update with analysis period property in callbacks
-add new table variables rather than replace 'hourly' part of loss adjustment factor

TODO: 
-Change percentages to fractions for period, constant loss portions of loss adjustment widget
-Update callbacks for loss adjustments to update analysis period, descriptive text
-hide 'hourly' factor in UI

Testing: file attached. 
[loss_factor_test.zip](https://github.com/NREL/SAM/files/9678500/loss_factor_test.zip)
Use loss_factor_updates branch in ssc. Test with detailed PV models

Fixes #703 (1 and 3)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by sjanzou — CHANGES_REQUESTED** [review]
Issue 1 - widget does not update with changes in analysis period:
25 year default
image

change to 10 year analysis period on "Financial Parameters" page and reopen widget - still lists analysis period as 25 years
image


Issue 2 - please include Lifetime losses in summary when enabled - maybe "Lifetime losses: enabled"
image

issue 3 - do not allow "Enable lifetime series losses (%)" for no lifetime models like PVWatts:
image

and solar water heating
image

**Comment by cpaulgilman** [comment]
In the Lifetime Array widget, the "analysis period" label is misleading because it is different from the analysis_period input on the Financial Parameters input page for non-lifetime performance models. Rename it to something like "Years in lifetime" or "Simulation years":

image

**Comment by mjprilliman** [comment]
> Issue 1 - widget does not update with changes in analysis period: 25 year default image
> 
> change to 10 year analysis period on "Financial Parameters" page and reopen widget - still lists analysis period as 25 years image
> 
> Issue 2 - please include Lifetime losses in summary when enabled - maybe "Lifetime losses: enabled" image
> 
> issue 3 - do not allow "Enable lifetime series losses (%)" for no lifetime models like PVWatts: image
> 
> and solar water heating image

Issue 1: This should be fixed with the most recent commit. 

Issue 2: Included in most recent commits. 

image

Issue 3: No we want to still use the hourly losses for PVWatts (and other non-lifetime models) or do we want to use the lifetime widget for all with simulation years set equal to 1? Could still be used to specify sub-hourly losses for non-lifetime.

**Comment by mjprilliman** [comment]
> In the Lifetime Array widget, the "analysis period" label is misleading because it is different from the analysis_period input on the Financial Parameters input page for non-lifetime performance models. Rename it to something like "Years in lifetime" or "Simulation years":
> 
> image
> 
> Also, add space between "losses" and "(%)":
> 
> image

Is there a label that works for both the Losses widget usage and the Merchant Plant usage? Otherwise this might be difficult to change

**Comment by sjanzou** [comment]
> > In the Lifetime Array widget, the "analysis period" label is misleading because it is different from the analysis_period input on the Financial Parameters input page for non-lifetime performance models. Rename it to something like "Years in lifetime" or "Simulation years":
> > image
> > Also, add space between "losses" and "(%)":
> > image
> 
> Is there a label that works for both the Losses widget usage and the Merchant Plant usage? Otherwise this might be difficult to change

@mjprilliman, @cpaulgilman, should we allow the losses to be tied to the analysis period and then apply them as such in the financial model? This is how the merchant plant works with PVWatts currently.

Another option would be to set the analysis period to 1 for non-lifetime models and then hide the "Analysis period" input in the widget.

**Comment by cpaulgilman** [comment]
> @mjprilliman, @cpaulgilman, should we allow the losses to be tied to the analysis period and then apply them as such in the financial model? This is how the merchant plant works with PVWatts currently.
>
> Another option would be to set the analysis period to 1 for non-lifetime models and then hide the "Analysis period" input in the widget.

For non-lifetime models like PVWatts, I think it would be ok to use this widget and set the "simulation years" value to 1.

**Comment by cpaulgilman** [comment]
@mjprilliman I noticed you changed the label for time series losses from (%) to (0-1). Are we going ahead with changing the widget from percentages to generic numbers? This has an implication for CSP models that use the widget to set a constant 4% availability loss, for example on the Physical Trough System Control page, and will require careful updating of defaults, and will impact PySAM users (including work of NREL CSP team).

**Comment by mjprilliman** [comment]
> @mjprilliman I noticed you changed the label for time series losses from (%) to (0-1). Are we going ahead with changing the widget from percentages to generic numbers? This has an implication for CSP models that use the widget to set a constant 4% availability loss, for example on the Physical Trough System Control page, and will require careful updating of defaults, and will impact PySAM users (including work of NREL CSP team).

We had discussed moving from % to 0-1 for this widget to give it more useable in other contexts in the future. If it is going to disrupt too many workflows I am happy to revert to % for this release and revisit later.

**Comment by mjprilliman** [comment]
> > > In the Lifetime Array widget, the "analysis period" label is misleading because it is different from the analysis_period input on the Financial Parameters input page for non-lifetime performance models. Rename it to something like "Years in lifetime" or "Simulation years":
> > > Also, add space between "losses" and "(%)":
> > 
> > 
> > Is there a label that works for both the Losses widget usage and the Merchant Plant usage? Otherwise this might be difficult to change
> 
> @mjprilliman, @cpaulgilman, should we allow the losses to be tied to the analysis period and then apply them as such in the financial model? This is how the merchant plant works with PVWatts currently.
> 
> Another option would be to set the analysis period to 1 for non-lifetime models and then hide the "Analysis period" input in the widget.

It seems setting analysis period to 1 is the agreed upon method so I will do that and modify the widget to hide the Analysis Period input in those cases.

**Comment by sjanzou** [comment]
Please test following file
image

Year 10 has 50% loss and Year 20 has 100% loss but not reflected in summary graph output
image

**Review by sjanzou — APPROVED** [review]
With latest changes in ssc pull request 878, I think this is good for lockdown testing.

Great work.

**Pull request merged**
