### PR TITLE
Fix callbacks for wind bos system cost options for hybrids

### LINKED ISSUE #1470: Wind Hybrids is Missing "Balance of System" Inputs
### Describe the bug

PV-Wind-Battery hybrids is missing the balance of system inputs

### To Reproduce

1. Open a wind hybrids case on develop
2. Click on Wind Installation Costs
3. Click on "Go to balance of system cost inputs"

### Expected behavior

Cost inputs should match stand alone wind.

### Screenshots

Hybrids:
image

Stand Alone Wind:
image

### PR DESCRIPTION
**Pull request by mjprilliman**
# Pull Request Template

## Description

-Hides button for Wind balance of system costs for hybrid systems
-Organizes wind hybrid callbacks into single function

Fixes #1470 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cpaulgilman** [comment]
I suggest also hiding the wind resource file `reference_resource_file` if it is not used for the turbine cost estimate -- I expected the turbine cost estimate to change with the weather file, but it doesn't. I think the wind resource file is only relevant for the BOS model.

**Review by cpaulgilman — APPROVED** [review]
Looks good, thanks!

**Comment by mjprilliman** [comment]
@sjanzou @cpaulgilman Do we know why the mac tests are failing on PR's?

**Comment by sjanzou** [comment]
> @sjanzou @cpaulgilman Do we know why the mac tests are failing on PR's?

@mjprilliman , tests pass locally - see issue https://github.com/NREL/SAM/issues/1479

**Pull request merged**
