### PR TITLE
Adjust widget for wave and tidal technologies

### LINKED ISSUE #1247: Loss Factor adjustment widget in wave, wave-battery, tidal models
### Is your feature request related to a problem? Please describe.

-Add loss factor adjustment to wave model for time series data

### Describe the solution you'd like

-Only show/enable widget for time series data
-Apply losses correctly for 1 hour data, 3 hour data of resource

### PR DESCRIPTION
**Pull request by mjprilliman**
## Description

-Adds adjust widget on shared losses page for wave, wave-battery and tidal (lifetime mode only accessible for wave-battery)
-Widget checks for timeseries data (as opposed to frequency matrix data), disables if timeseries resource data is not being used
-Adds Three Hour data to timeseries loss dropdown, ssc checks for misalignment of three hour data with resource data for all technologies same as hourly and subhourly data

Fixes #1247 

Goes with https://github.com/NREL/ssc/pull/1225

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change modifies variables in existing compute modules. Please see [Checking for PySAM Incompatible API Changes](https://github.com/NREL/SAM/wiki/Checking-for-PySAM-Incompatible-API-Changes).

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by cpaulgilman — CHANGES_REQUESTED** [review]
If I set Marine Wave Three Hourly loss and run a simulation, the next time I open the adjust widget, the time series mode reverts to Subhourly mode. For other technologies, the time series mode opens in the same state as the last time I closed it.

**Comment by cpaulgilman** [comment]
Help revision for Marine Energy Wave and Marine Energy Tidal chapters:

## Losses

image

**Comment by mjprilliman** [comment]
> If I set Marine Wave Three Hourly loss and run a simulation, the next time I open the adjust widget, the time series mode reverts to Subhourly mode. For other technologies, the time series mode opens in the same state as the last time I closed it.

Thanks for catching that Paul. I think my recent commit fixes this issue. The help documentation looks good.

**Comment by mjprilliman** [comment]
> If I set Marine Wave Three Hourly loss and run a simulation, the next time I open the adjust widget, the time series mode reverts to Subhourly mode. For other technologies, the time series mode opens in the same state as the last time I closed it.

Thanks for catching that Paul. I think my recent commit fixes this issue. The help documentation looks good.

**Review by cpaulgilman — APPROVED** [review]

**Pull request merged**
