### PR TITLE
Updates to Documentation

### PR DESCRIPTION
**Pull request by dguittet**
# Pull Request Template

## Description

1. Update the PySAM Documentation to provide important Note about `default` model initializer

image

2. Also add print statements to run_default_diffs.py for debugging purposes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cpaulgilman** [comment]
@dguittet Please consider this text or similar for the description:

The default configuration is a collection of default values for the module inputs. Some inputs may not be included in the default configuration and are automatically assigned the value indicated by the variable's 'Required' attribute.

**Comment by dguittet** [comment]
@cpaulgilman Thanks for the suggestion, I've updated to use that.

**Comment by cpaulgilman** [comment]
> @cpaulgilman Thanks for the suggestion, I've updated to use that.

Did you push that commit? I'll approve it when I see it here. ;)

**Review by cpaulgilman — APPROVED** [review]

**Comment by dguittet** [comment]
Thanks @cpaulgilman !

**Pull request merged**
