### PR TITLE
addresses SAM issue 1455

### PR DESCRIPTION
**Pull request by sjanzou**
Goes with https://github.com/NREL/wex/pull/165

Sort order for technology tree specified in startup.lk as (note that not all technologies have to be specified):
image

Which results in configuration window display as:
image

If no "TechnologyTreeOrder" configopt specified in startup.lk, the result is how items appear in startup.lk:
image

The financial tree and page order sorting has not yet been implemented. 

Will proceed based on this pull request feedback

### CODE REVIEW

**Comment by mjprilliman** [comment]
Is there a way to clear the input page selection from the tree when the Results button next to Simulate is pressed? If you do steps:

1. Click Simulate
2. From Results page click an input page to return to inputs.
3. Click Results button to right of Simulate to return to Results
4. Click on still highlighted input page in tree. 

Nothing happens. The easy workaround is to select a different input page. There is also the question of the Results button being disabled, which has it's own issue #1485

**Review by cpaulgilman — APPROVED** [review]
Configuration Tree sorting works as advertised in Linux (Mint 21.1).

With sorting in startup:

tech-tree-sorted

Without sorting, Hybrid is at bottom:

tech-tree-not-sorted

Note that in Linux, selected technology is white (invisible) when financing is selected (not a high priority to fix):

tech-tree-invisible-tech

**Comment by sjanzou** [comment]
> Is there a way to clear the input page selection from the tree when the Results button next to Simulate is pressed? If you do steps:
> 
> 1. Click Simulate
> 2. From Results page click an input page to return to inputs.
> 3. Click Results button to right of Simulate to return to Results
> 4. Click on still highlighted input page in tree.
> 
> Nothing happens. The easy workaround is to select a different input page. There is also the question of the Results button being disabled, which has it's own issue #1485

Updated with latest commit - please retest.

**Comment by sjanzou** [comment]
tested RHEL 8.6, MacOS 14.0 and Windows 11

image

**Pull request merged**
