### PR TITLE
Group, label updates for mhk, geo ui pages

### PR DESCRIPTION
**Pull request by mjprilliman**
## Description

Fix Group label and some description labels for geothermal and marine UI pages

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by cpaulgilman — CHANGES_REQUESTED** [review]
### Geothermal 

looks good.

### Marine Help

In the Startup script, please set the 'help' parameter for all 'Marine Costs - xxx' pages for both Tidal and Wave to 'cc_marine_energy'. We have one Help topic to explain how to use the capital cost widgets that should work for all of the different Capital Cost input pages.

### Marine Tidal

looks good.

### Marine Wave

looks good

**Comment by mjprilliman** [comment]
I will update the label errors. 

On the callback errors I'm going to have to meet with you to discuss further because I am not seeing any of those on my end.

**Comment by cpaulgilman** [comment]
> On the callback errors I'm going to have to meet with you to discuss further because I am not seeing any of those on my end.

Let me try a clean rebuild and see if that fixes it. Could be something on my end.

**Comment by cpaulgilman** [comment]
@mjprilliman I rebuilt this and is working fine now -- see revised feedback above. Sorry for the initial review based on a bad build.

One comment is that the UIObject attribute of cost inputs is Default instead of the appropriate widget name. Not a big deal, but ideally these should be set correctly for the Inputs Browser (especially for ListBox objects, which also need the Index Labels attribute).

image

**Review by cpaulgilman — APPROVED** [review]

**Pull request merged**
