### PR TITLE
add value lines to ensure reopt dispatch runs with reopt's constraints

### LINKED ISSUE #1092: REopt dispatch should use same load/pv constraints as REopt
REopt assumes that batteries can discharge to push PV onto the grid and charge while the grid is meeting load, but the "get size and dispatch" button does not adjust for these constraints. The screenshot below shows the dispatch page after getting size and dispatch:

image

The two boxes at the bottom should be unchecked for REopt dispatch.

### PR DESCRIPTION
**Pull request by brtietz**
# Pull Request Template

## Description

Add value settings to the REopt sizing script such that we run REopt with the REopt friendly dispatch constraints.

Fixes #1092 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cpaulgilman** [comment]
@brtietz I am getting a series of "Save inputs as" dialogs saving files with invalid names like ssc-/ssc-pvsamv1.lk.lk followed by a UI callback error:

```
Could not evaluate callback function:call_reopt->on_change
[73]: error in call to 'reopt_size_battery()': SSC requires input 'subarray1_rear_soiling_loss', but was not found in the SAM UI or from previous simulations[5]: eval error in statement list
```

Also, the initial msgbox() that opens asking about changing inputs on the battery dispatch page should be made more general now that the script changes more of those check boxes:

Old:
>REopt requires that battery can charge from grid.
>
>Change Battery can Charge from Grid input on Battery Dispatch page automatically? Click No to exit optimization.
>

Suggested New:
>REopt requires specific battery dispatch options.
>
>Change these options automatically on the Battery Dispatch page? Click No to exit optimization.
>

**Comment by cpaulgilman** [comment]
In my tests (in sam-private so I could run the REopt API call), I am getting errors like the following:

```
Could not evaluate callback function:call_reopt->on_change
[67]: error in call to 'reopt_size_battery()': Invalid inputs. See 'input_errors'.
[ losses value (1.14904) in Scenario>Site>PV exceeds allowable max 0.99 ][5]: eval error in statement list
```

The following change to [Line 5773](https://github.com/NREL/SAM/blob/f0b33aa22d6ca35328fac58eca9ae2af9e4bbf5d/src/invoke.cpp#L5773) of invoke.cpp dividing the loss by 100 to convert from percent to decimal seems to fix the problem:

image

I'm not sure exactly what is going on here because the [REopt API inputs documentation](https://github.com/NREL/REopt-API-Analysis/wiki/Job-Inputs) does not list losses as an input.

**Comment by brtietz** [comment]
Oh, sorry, @Matthew-Boyd and I have a plan to fix this that he hasn't had a chance to execute yet, sorry to waste your time testing it again now.

I think that might be the link to the REopt V2 documentation - I can't find the link to the older, more comprehensive documentation, but "losses" is a variable in the code: https://github.com/NREL/REopt.jl/blob/master/src/core/pv.jl

Relatedly, I wasn't sure I should make an issue about upgrading to the V2 endpoint, since this issue exists: https://github.com/NREL/SAM/issues/1135

**Comment by cpaulgilman** [comment]
No need for a different issue, I added a note to #1135 to considering updates.

**Comment by brtietz** [comment]
@cpaulgilman Ok, this is finally ready for a second review. Please check out https://github.com/NREL/ssc/pull/925 if it hasn't been merged prior to your review of this PR.

**Review by cpaulgilman — APPROVED** [review]
Looks good. I fixed the message box text, one for each input check is good for clarity. Resulting NPV is big improvement over SAM 2021.12.02, and dispatch schedule is completely different when using gen as REopt input instead of lat/lon with a loss.

**Comment by sjanzou** [comment]
@cpaulgilman, @brtietz, the sam_1092_update_reopt_script pythonhandler.cpp fails to load on MacOS (found while trying to test lk pull request 36)
image

**Comment by sjanzou** [comment]
> @cpaulgilman, @brtietz, the sam_1092_update_reopt_script pythonhandler.cpp fails to load on MacOS (found while trying to test lk pull request 36) image

This issue is not specific to develop but is caused by a bogus python_config.json that was checked in in commit c3af95
image
 This means that the current release candidate will fail if someone has not run landbosse before! We need to prevent the python_config.json to be checked in - I am going to put on the .gitignore after fixing.

**Pull request merged**
