### PR TITLE
Version upgrade fixes

### PR DESCRIPTION
**Pull request by mjprilliman**
## Description
-Cleanup to version upgrade based on release testing
-UI labels on PV module page to make update to library variable names less confusing on upgrade
-Cleanup of MSLF MIMO to avoid equation error
-Updating of generic system variable names, config name

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change modifies variables in existing compute modules. Please see [Checking for PySAM Incompatible API Changes](https://github.com/NREL/SAM/wiki/PySAM-Incompatible-API-Changes-&-Regenerating-PySAM-Files).
- [ ] This change requires updating the PySAM files via export_config. Please see [When do the PySAM files need to be regenerated?](https://github.com/NREL/SAM/wiki/PySAM-Incompatible-API-Changes-&-Regenerating-PySAM-Files#when-do-the-pysam-files-need-to-be-regenerated-via-export_config)

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by sjanzou — APPROVED** [review]
GitHub Actions failing because default configurations do not run... e.g. Standalone Battery:
image

Updated all configurations with issues and reran defaults. 
The version upgrade seems to be working!

**Review by taylorbrown75 — APPROVED** [review]
Thanks for finding and fixing the MSLF system design bug! I set the aux and bop calculated variables (SC_CALC_bop, SC_CALC_aux) to the failure integer if the cmod fails. 

I also fixed a version upgrade error related to the new TES model.

**Comment by cpaulgilman** [comment]
I'm working to make the message clearer so that users can see what the variable name change is. This may be useful for PySAM and SDK users. I'll add a commit when that's ready

Right now, the messages make it look like the variable's value changed:

image

**Comment by cpaulgilman** [comment]
@taylorbrown75 Could you test my latest changes to make sure they work with any special cases of old IPH/CSP files you might have?

**Comment by taylorbrown75** [comment]
> @taylorbrown75 Could you test my latest changes to make sure they work with any special cases of old IPH/CSP files you might have?

@cpaulgilman Thank you for making those changes, the version upgrade is much clearer now. I tested old files and everything works!

**Review by cpaulgilman — APPROVED** [review]

**Pull request merged**
