### PR TITLE
Rename Generic System technology to Custom Generation Profile

### LINKED ISSUE #1849: Consider renaming Generic System model
### Is your feature request related to a problem? Please describe.
-Consider renaming generic system model to better capture the ability to input measured plant data or come up with custom energy timeseries data
### Describe the solution you'd like

-'Custom Power Plant' or 'Power Plant Data', etc. 

### Additional context

-Noticed during SAM retreat.

### PR DESCRIPTION
**Pull request by mjprilliman**
## Description

-Rename all Generic System configs and references to Custom Generation Profile:
-Update configs in startup, reference former name in technology tree setup
-Update UI forms and defaults files
-Update references in metrics.lk, autographs.lk, version upgrade, etc. 
-Key word replace in help system, update file names (@cpaulgilman need to see if help system builds correctly, if not will have to revert and try another way). 
-Update hybrid configs with custom generation, battery configs as well
-Update API, export_config

Fixes #1849 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change modifies variables in existing compute modules. Please see [Checking for PySAM Incompatible API Changes](https://github.com/NREL/SAM/wiki/Checking-for-PySAM-Incompatible-API-Changes).

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cpaulgilman** [comment]
> -Key word replace in help system, update file names (@cpaulgilman need to see if help system builds correctly, if not will have to revert and try another way).

Help revisions need to be done to the proprietary source files using the Help & Manual software. Editing the HTML files in the code repository will not work because they are replaced by the HTML output of Help & Manual. I will make the necessary changes to Help in a separate pull request for the Fall 2024 release.

**Review by cpaulgilman — CHANGES_REQUESTED** [review]
In configuration tree, remove "formerly".

Change "Power Plant" in navigation menu to "Generation Profile" For CustomGeneration and Custom Generation-Battery configuration.

On Custom Generation Plant form:

* Change "Custom Generation Profile Power Plant" group label to "Custom Generation Profile".

* Change "Power Plant Losses" divider label to "Losses"

* Change group for all variables from "Generic System Plant" to "Custom Generation Profile".

On Custom Generation Costs form, change group for all variables from "Generic System Capital Costs" to "Custom Generation Capital Costs".

On Custom Generation Battery Costs form, change group for all variables from "Generic Battery Capital Costs" to "Custom Generation Battery Capital Costs".

**Comment by cpaulgilman** [comment]
> > -Key word replace in help system, update file names (@cpaulgilman need to see if help system builds correctly, if not will have to revert and try another way).
> 
> Help revisions need to be done to the proprietary source files using the Help & Manual software. Editing the HTML files in the code repository will not work because they are replaced by the HTML output of Help & Manual. I will make the necessary changes to Help in a separate pull request for the Fall 2024 release.

I will update the Help source files, generate a new set of HTML files, and commit them to this branch so we can make sure Help is working properly before merging.

**Review by cpaulgilman — COMMENTED** [review]
For hybrid CustomGeneration-PVWatts-Wind-FuelCell-Battery configuration, the fuel cell capacity and custom generation capacity on the Hybrid System page is zero instead of being the value from the Custom Generation Profile and Fuel Cell input pages, respectively.

hybrid-zero-capacity

**Comment by mjprilliman** [comment]
> For hybrid CustomGeneration-PVWatts-Wind-FuelCell-Battery configuration, the fuel cell capacity and custom generation capacity on the Hybrid System page is zero instead of being the value from the Custom Generation Profile and Fuel Cell input pages, respectively.
> 
> hybrid-zero-capacity

There were a few missing updates in variable names and string checks in the UI equations for Hybrid System and Hybrid Cost pages, should be fixed with latest push.

**Comment by cpaulgilman** [comment]
I found one more thing. Fuel Cell cost is missing from the Hybrid System Costs page for CustomGeneration-PVWatts-Wind-FuelCell-Battery configurations:

image

**Comment by mjprilliman** [comment]
> I found one more thing. Fuel Cell cost is missing from the Hybrid System Costs page for CustomGeneration-PVWatts-Wind-FuelCell-Battery configurations:
> 
> image

Fixed the callback for this.

**Review by cpaulgilman — APPROVED** [review]
Looks good! Thanks for sorting through all of those changes.

**Pull request merged**
