### PR TITLE
Marine, Geothermal UI fixes

### PR DESCRIPTION
**Pull request by mjprilliman**
## Description

-Mac UI overlap issues addressed
-Fix show/hide issues with marine costs
-Change units of geothermal reservoir_pressure_change variable
-Update wave, tidal resource library columns and example files

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by janinefreeman** [comment]
@cpaulgilman I can check everything in this PR except the Mac forms.

**Review by janinefreeman — APPROVED** [review]
Reviewed everything except Mac/Linux spacing, all looks good with latest commit

**Comment by cpaulgilman** [comment]
> Reviewed everything except Mac/Linux spacing, all looks good with latest commit

@janinefreeman Can you check this again after I merged in `ui-mac-fixes`? I'm getting a mimo error for Geothermal -- do you see that in Windows?

**Comment by mjprilliman** [comment]
> > Reviewed everything except Mac/Linux spacing, all looks good with latest commit
> 
> @janinefreeman Can you check this again after I merged in `ui-mac-fixes`? I'm getting a mimo error for Geothermal on a Mac -- do you see that in Windows?

Just for a sanity check did you have the same branch name checked out in ssc?

**Comment by cpaulgilman** [comment]
> > > Reviewed everything except Mac/Linux spacing, all looks good with latest commit
> > 
> > 
> > @janinefreeman Can you check this again after I merged in `ui-mac-fixes`? I'm getting a mimo error for Geothermal on a Mac -- do you see that in Windows?
> 
> Just for a sanity check did you have the same branch name checked out in ssc?

Ah, missed that.

**Review by cpaulgilman — APPROVED** [review]

**Pull request merged**
