### PR TITLE
Read ITC array values in output reports

### LINKED ISSUE #1226: Output reports printing nan ITC
### Describe the bug

ITC federal and state variables being changed to arrays breaks the report templates and prints nans. I am working on a fix. 

### To Reproduce

1. Go to Detailed PV, Single Owner
2. Create Report
3. Look at incentives box on Page 1

### Expected behavior

Reports should work similar to PTC printing in reports

### PR DESCRIPTION
**Pull request by mjprilliman**
# Pull Request Template

## Description

-Change report templates to read ITC federal and state as arrays rather than numbers. 

Fixes #1226 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by cpaulgilman — CHANGES_REQUESTED** [review]
When ITC is an array of more than one value, I don't think it makes sense to report the average over the analysis period in the PDF report. (The PBI applies to annual production every year, so reporting the average over the analysis period is somewhat meaningful, but the ITC applies to the installation cost only in the years where the percentage is not zero.) For ITC it might make more sense to report the sum of the array values instead of their average, and put "total" in parentheses instead of "average".

@sjanzou, what do you think?

**Comment by mjprilliman** [comment]
Updated mini-grid example to latest version as otherwise Version upgrade window is blocking user interface and can't close it without exiting the wizard first. Thoughts @sjanzou @cpaulgilman ?

**Comment by cpaulgilman** [comment]
> Updated mini-grid example to latest version as otherwise Version upgrade window is blocking user interface and can't close it without exiting the wizard first.

I agree with updating the mini-grid-example.sam file to the current version so the upgrade script does not run -- we should add that to the pre-release checklist. I think that is the only .sam file in the distribution.

**Comment by sjanzou** [comment]
> Updated mini-grid example to latest version as otherwise Version upgrade window is blocking user interface and can't close it without exiting the wizard first. Thoughts @sjanzou @cpaulgilman ?

Thanks for updating the mingrid sam file - that should be one more thins off of the pre-release checklist!

**Comment by sjanzou** [comment]
> When ITC is an array of more than one value, I don't think it makes sense to report the average over the analysis period in the PDF report. (The PBI applies to annual production every year, so reporting the average over the analysis period is somewhat meaningful, but the ITC applies to the installation cost only in the years where the percentage is not zero.) For ITC it might make more sense to report the sum of the array values instead of their average, and put "total" in parentheses instead of "average".
> 
> @sjanzou, what do you think?

@cpaulgilman, yes, I agree, the sum is the most meaningful single metric for the ITC array.

**Pull request merged**
