### PR TITLE
Replace JSONcpp with RapidJSON

### PR DESCRIPTION
**Pull request by sjanzou**
run export_config, defaults, ssc tests and landbosse

### CODE REVIEW

**Comment by sjanzou** [comment]
Partially addresses issue  #504 and #486

**Comment by sjanzou** [comment]
goes with ssc pull request 664 https://github.com/NREL/ssc/pull/664

**Review by cpaulgilman — APPROVED** [review]
I tested some of the SAM UI functions that use JSON, including URDB downloads, NSRDB, Cambium, marine wave resource, and all are working. These are still using wxWidgets JSON tools. Perhaps we should not change these until a later update.

**Comment by sjanzou** [comment]
> I tested some of the SAM UI functions that use JSON, including URDB downloads, NSRDB, Cambium, marine wave resource, and all are working. These are still using wxWidgets JSON tools. Perhaps we should not change these until a later update.

@cpaulgilman, that is correct... this pull request only replaces JSONcpp with RapidJSON and the SAM dependencies for this are in the landbosse and pythonhandler code used. We are now down to wxJSON and RapidJSON with this pull request and will eliminate wxJSON in another pull request.

**Pull request merged**
