### PR TITLE
Address SAM issue #1928

### PR DESCRIPTION
**Pull request by sjanzou**
LandBOSSE 2.3.0.3 is latest PyPi package and supports Python 3.7 only - numpy 1.4.5 requirements do not work with later Python versions. Later LandBOSSE version 2.5.0 has to be installed locally if used with later versions of Python. install_python.ps1 updated to work with Python 3.7 since get-pip.py requires 3.8 or later.

### CODE REVIEW

**Review by brtietz — APPROVED** [review]
Works on Windows!

**Review by mjprilliman — COMMENTED** [review]
This worked for me on SAMOS, but I still get a Python install callback error when trying to run it from SAM private.

**Comment by sjanzou** [comment]
> This worked for me on SAMOS, but I still get a Python install callback error when trying to run it from SAM private.

@mjprilliman , please delete you SAM-private\build_windows folder and rebuild SAM-private and test... that worked for me ;-)

**Comment by sjanzou** [comment]
Build and tested with SAM-private on RHEL 8.6
image

**Comment by sjanzou** [comment]
Working as universal binary app on MacOS 15.1
image

**Pull request merged**
