### PR TITLE
Cambium update to 2022

### LINKED ISSUE #1104: Link to 2021 Cambium Data
The merchant plant defaults to calling the 2020 cambium data. 2021 provides additional scenarios, such as 95% renewables by 2035. Add this to the data download options.

Also consider including "busbar" data in addition to "end use" data.

Update LK sample scripts with any changes to Cambium API calls in SAM.

### PR DESCRIPTION
**Pull request by cpaulgilman**
# Pull Request Template

## Description

Fixes #1104 and #1098

Updates Cambium downloads to Cambium 2022 and makes it easier to update in the future.

Add escalation rate for multiple year option, and support Cambium years in any interval (Cambium 2020 was even years, Cambium 2022 is even years 2024-2030 and then every five years 2030-2050).

Adds macro and button for PPA models to download cambium pricing data: See Revenue page for Single Owner model and Time of Delivery page for others.

Updates sample script for Cambium downloads.

Fixes Merchant plant layout for Mac and Linux.

Includes Help revisions.

To test in Merchant Plant:

* Download single year
* Download multiple years, varying the start year
* Set escalation rate for multiple years and verify prices in out years are correct
* Review UI text, tooltips and Help description

To test in PPA models:

* Try download button on Revenue page (single owner) Time of Delivery Factors page (other models)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update
- [ ] This change modifies variables in existing compute modules. Please see [Checking for PySAM Incompatible API Changes](https://github.com/NREL/SAM/wiki/Checking-for-PySAM-Incompatible-API-Changes).

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by sjanzou — COMMENTED** [review]
Added SAM-private pull request 87 to go along with this pull request to update webapis.conf in SAM-private to prevent a hard crash.

Results with escalation seem a little weird in year 22 of the attached file with spreadsheet with corrected timestamps.... Maybe Cambium data has some weird values in 2045?
image


[SAM_1365.zip](https://github.com/NREL/SAM/files/10891551/SAM_1365.zip)

**Comment by cpaulgilman** [comment]
@sjanzou Thanks -- I fixed a mistake in applying the escalation rate to years copied from previous available cambium years.

Here is a detailed Excel spreadsheet that replicates copying previous years and escalation calculations.

[cambium-test.zip](https://github.com/NREL/SAM/files/10902183/cambium-test.zip)

**Comment by brtietz** [comment]
Unfortunately, even after Steve's fix, PVWatts-Merchant Plant still crashes for me when I click on the "revenue" tab (I have cambium-update-to-2022 checked out on SAM and sam-private). The debugger has an opaque compliant about a read access violation and an lk:error_t.

**Comment by cpaulgilman** [comment]
@brtietz SAM-private worked for me. I reran cmake and did a clean build to make sure all of the files were copied over from SAM.

**Comment by brtietz** [comment]
> @brtietz SAM-private worked for me. I reran cmake and did a clean build to make sure all of the files were copied over from SAM.

Ah, thanks. Doing a clean build fixed the crash. I'll do a deeper review tomorrow.

**Review by sjanzou — APPROVED** [review]
Cashflow looks much better - thanks for updating
image

**Comment by brtietz** [comment]
Thanks, this is some great functionality!

My one comment is it's not clear to me why the escalation rate would only be available for multi-year downloads for the merchant plant. Since single year data repeats for the lifetime, I would (and I imagine other users would as well) really like to be able to escalate single year data at the same rate as inflation. This would also more closely match the capabilities of the PPA models. Was there a reason that feature was disabled by default?

**Comment by cpaulgilman** [comment]
@brtietz Oh, right! I guess I got caught up in the excitement of the multi-year implementation. Escalation is enabled for both single-year and multi-year downloads and Help revised accordingly as of my last commits.

**Review by brtietz — APPROVED** [review]

**Pull request merged**
