### PR TITLE
Wave model JPD generator UI cleanup

### PR DESCRIPTION
**Pull request by mjprilliman**
## Description

-UI updates to separate wave model JPD generator into its own group box. Descriptive text with reference to marine energy standard included. 
-Cleanup of file handling for adding wave resource folders to library
-Changing JPD LK functions to return name of file in order to properly index file in 'Frequency of Occurence' library

Potential direct quote from IEC/TS 62600-100 standard to include in help documentation: 

“Where a time series of the wave energy resource is available the MAEP shall be calculated in accordance with mathematical Formula (12). A minimum of 10 years of wave energy resource data should be used for the calculation of the mean annual energy production. If the mean annual energy production is calculated with less than 10 years of wave energy resource data this shall be noted explicitly. The wave energy resource data set shall be unbiased, containing the number of sea-states for each month proportional to the number of days in the month.” 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by mjprilliman** [comment]
@cpaulgilman could you review the label text in the 'Time Series' UI for the JPD generator button?

**Comment by cpaulgilman** [comment]
@mjprilliman Do you have a specific request to include all of that information in the UI text? I would prefer to provide a brief description in the UI text and a more detailed description in Help. Let me know either way and I will revise the text accordingly.

Also, the very wide group boxes (width = 1270) make the Wave Resource page a little harder to use. I think it would be best to limit the width to around 1000. I generally try to use the same width for all of the UI forms for a given configuration so that they don't jump around as you switch between pages, although that is not always possible.

**Comment by mjprilliman** [comment]
> @mjprilliman Do you have a specific request to include all of that information in the UI text? I would prefer to provide a brief description in the UI text and a more detailed description in Help. Let me know either way and I will revise the text accordingly.
> 
> Also, the very wide group boxes (width = 1270) make the Wave Resource page a little harder to use. I think it would be best to limit the width to around 1000. I generally try to use the same width for all of the UI forms for a given configuration so that they don't jump around as you switch between pages, although that is not always possible.

No specific requests on the UI text, I wasn't sure how much detail to include. Happy to get your revisions on the UI text. 

I will update the width of the group boxes.

**Comment by cpaulgilman** [comment]
@mjprilliman I committed revised text for the UI. I will make revisions to Help, and commit those separately with other help revisions before the release.

**Review by cpaulgilman — APPROVED** [review]

**Pull request merged**
