### PR TITLE
Checking for SDK/PySAM Incompatible API Changes

### PR DESCRIPTION
**Pull request by dguittet**
## Description

Certain changes to compute modules will cause incompatible API changes for PySAM. This will require a new Major version and will also potentially force users to change their PySAM scripts to handle these new changes if they should update to the new Major version. Therefore, pull requests that will cause these incompatibilities need to be appropriately recorded for documentation and PySAM releasing.

### Updates Script to Diff SAM Default Values and SSC Variables

The `SAM-Dev/sam/test/run_defaults_diff.py` script can be used to compare the current branch on the local machine against the most recent released SAM. The most recent released SAM is downloaded from both sam.nrel.gov for the ssc binaries and from github.com for the default files. These are compared with the binaries built on the local machine (or Github action machine) and the defaults in the local branch from the SAM repo.

The outputs are SSC variables and SAM defaults in a JSON file.

This script is run automatically with every Github Action. Go to Actions, select a workflow run, scroll to the Artefact section at the bottom to find "SSC Var & SAM Defaults Diff"

### Updates to Documentation

New wiki page: https://github.com/NREL/SAM/wiki/Checking-for-PySAM-Incompatible-API-Changes

Added wiki page to pull_request_template

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by sjanzou — CHANGES_REQUESTED** [review]
This branch failed to build with wxWidgets 3.2.0 used on develop. I merged develop into this branch and then SAM built without issue. The differ seems to be working well and is very useful. Please review the merge and make sure your local build is made with wxWidgets 3.2.0 before merging into develop. Thanks!

**Comment by dguittet** [comment]
sorry I'm not sure why I closed this? butterfingers or something...

**Comment by dguittet** [comment]
@sjanzou Tests are passing now. Where there any specific changes you wanted me to make?

**Review by sjanzou — APPROVED** [review]
@dguittet, everything appears to be working fine now with wx3.2.0. Thanks!

**Comment by dguittet** [comment]
Thanks @sjanzou !

**Pull request merged**
