### PR TITLE
Contour plot of system power generated on summary page

### PR DESCRIPTION
**Pull request by mjprilliman**
-Contour plot of 365 days by 24 hours showing kW generated each hour
-Available for all models with time series outputs
-Matches appearance of year 1 data on Heatmaps tab

### CODE REVIEW

**Review by sjanzou — APPROVED** [review]
Looks good! We may want to change to months along the bottom in another pull request.

**Review by cpaulgilman — COMMENTED** [review]
In this example for Detailed PV / Single Owner, I'm confused by the kWh units in the title, and the hours in the x-axis that go to 365. I was expecting kW and 8760 given that the values in the legend appear to be kW.

image

**Comment by mjprilliman** [comment]
> In this example for Detailed PV / Single Owner, I'm confused by the kWh units in the title, and the hours in the x-axis that go to 365. I was expecting kW and 8760 given that the values in the legend appear to be kW.
> 
> image

Did you pull the latest changes on this branch? When I run that example I get the following: 

image

As for the axes, the graph is 24 hours/day by 365 days/year = 8760 hours/year for the first year. This matches the Heatmap graph for the first year of the analysis.

**Comment by cpaulgilman** [comment]
I built my test version from SSC branch https://github.com/NREL/ssc/tree/heatmap_day_by_hour. Should I build from patch branch of SSC instead?

**Comment by sjanzou** [comment]
@mjprilliman, will these changes go into patch and develop ssc and SAM?

**Comment by mjprilliman** [comment]
> @mjprilliman, will these changes go into patch and develop ssc and SAM?

Yes, once I resolve the Travis test issues these changes will go into patch and develop.

**Comment by sjanzou** [comment]
Linux build fails due to trying to merge into patch with failing main.cpp from develop that was merged into heatmap_month_by_day. I thought the procedure was to branch off of patch for anything to go into patch and then after patch is running to merge into develop.

The specific issue is due to the following:
main.cpp line 2809 trying to use a void return as a boolean. 

/home/sjanzou/Public/Projects/GitHub/NREL/SAM/src/main.cpp:2809:49: error: could not convert ‘set_python_path(python_path.std::basic_string<_CharT, _Traits, _Alloc>::c_str<char, std::char_traits<char>, std::allocator<char> >())’ from ‘void’ to ‘bool’
         if (!set_python_path(python_path.c_str()))

The develop branch of ssc has set_python_path returned as an int so can ve converted to bool, so the develop branch of ssc works with the develop branch of SAM. 

In this pull request, if the develop branch of ssc is used, then everything will build and if the patch branch of ssc is used (as on Travis-CI) everything will fail. 

So, we need to keep all the dependent repos on the same root branch (either patch or develop) and be sure not to merge develop into a pull request branch that requests being merged into patch. 

Hopefully, this makes sense. Revising and resubmitting this pull request now...

**Comment by mjprilliman** [comment]
Closing this branch because the root branches were messed up. The additions were added in a new PR.

**Pull request closed without merging**
