### PR TITLE
Batt UI reorgazine inputs

### PR DESCRIPTION
**Pull request by cpaulgilman**

### CODE REVIEW

**Comment by cpaulgilman** [comment]
I need to add defaults for Fuel Cell configurations before merging this.

**Review by mjprilliman — APPROVED** [review]
Looks good to me once the Fuel Cell defaults are updated

**Comment by mjprilliman** [comment]
@cpaulgilman I believe this is good to merge now. The batt_sizing_bug_fix merge changed .travis.yml to "develop" but merging patch in changed it back to "patch". @brtietz is that correct?

**Comment by brtietz** [comment]
@mjprilliman Yes, the updated travis config is working as expected for this branch.

**Pull request merged**
