### PR TITLE
Update Advanced NSRDB Downloads for latest NSRDB

### LINKED ISSUE #1534: Advanced NSRDB download updates
1. Consider removing Full Disc results from list (or could show/hide with checkbox).

2. Auto-select from PSM v3 check boxes should be for psm3-2-2 instead of psm3:
    * Add check box for 15-minute data (see note below).
        image
    * Consider removing TGY and TDY check boxes

3. Consider adding row for "Autoselect from psm3-5min, which is useful for recent 15-minute data to correlate with measured load data for recent years, but only contains data from 2018-2022 compared to 1998-2022 for psm3-2-2.

4. Update for new Africa/Europe data, see https://github.com/NREL/SAM/issues/1719

5. Fix wxWidgets debug errors.

6. Fix alignment and layout.

### PR DESCRIPTION
**Pull request by cpaulgilman**
Advanced NSRDB Downloads should now work properly for all NSRDB datasets.

* Download all attributes (DNI, GHI, temperature, etc.) provided by NSRDB instead of selecting ones used by SAM. This increases file size (especially for [PSM V3.2.2](https://developer.nrel.gov/docs/solar/nsrdb/psm3-2-2-download/) that has several attributes SAM does not need like ghuv-280-400) but reduces maintenance requirements because we no longer need to update attribute lists in SAM as NSRDB is updated.

* Add check boxes for 15- and 10-minute data provided by some endpoints. Automatically enable/disable checkboxes based on 'interval' and 'year' information in Solar Data Query response instead of based on dataset name.

Requires building SAM-private to test:

1. Create a solar case (financial model not required).
2. On Solar Resource page, click **Advanced Download**.
3. For the location, try as many lat/lon and location names as possible, and click all checkboxes and buttons to test for functionality and possible errors.
4. Click **OK** for at least some locations to download and verify weather files work.

The following is a list of locations to test most, if not all of the NSRDB endpoints:

Anchorage, Alaska
Manila, Philippines
Fuzhou, China
Hanoi, Vietnam
Baoshan, China
Lucknow, India
Jaipur, India
Ghardaia, Algeria
Arrecife, Canarias
Calheta, Azores
Mindelo, Cape Verde
Santo Domingo, Dominican Republic
Kauapushishkat, Canada
Wollaston Lake, Canada
Chignik, Alaska
Rochester, New York
Crawford, Nebraska
Kaunakakai, Hawaii
Puuwai, Hawaii
London, Kiribati
Rapa Iti, French Polynesia
Auala, Samoa
Alice Springs, Australia
Dunedin, New Zealand
Manaus, Brazil
Puerto Santa Cruz, Argentina
Lubumbashi, Democratic Republic of Congo

Fixes #1534

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change modifies variables in existing compute modules. Please see [Checking for PySAM Incompatible API Changes](https://github.com/NREL/SAM/wiki/Checking-for-PySAM-Incompatible-API-Changes).

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cpaulgilman** [comment]
The NSRDB does not have data for locations higher than 60 degrees North latitude:

image

Chignik is at about 56 degrees N, and Anchorage is at about 61 degrees N.

**Review by sjanzou — APPROVED** [review]
Nit picking because I have been developing and UI for another project - should all of the filtering controls and OK button be disabled until the list box has some entries (note this has never been the case and is probably another issue)
image

Nice message for the middle of the ocean
image
 but does not clear results (shown from previous search and inconsistent with Location - again another issue):
image

For this issue - I have found all working and simulating
image

Nice message at end of long download
image

64 degrees north
image

Unicode working:
image

Shetland Islands (maybe north of 60 deg working...
image

**Comment by cpaulgilman** [comment]
> Shetland Islands (maybe north of 60 deg working...

Interesting case: Geocode API returns 60.187,-1.429. Nearest NSRDB grid cell center is at 59.97,-1.42, so it falls within the NSRDB coverage area with Lat < 60.

**Comment by cpaulgilman** [comment]
@sjanzou Thank for nit picking! Please review my latest commit that should fix these issue.

**Review by brtietz — APPROVED** [review]
The change looks good! It looks like this also works for the meteosat data as well, I was able to get weather files for London, England and Paris with the code on this branch.

**Pull request merged**
