### PR TITLE
Add cf input to tidal turbine design page

### PR DESCRIPTION
**Pull request by mjprilliman**
## Description

-Expose target capacity factor input for tidal turbine design feature
-Was previously an assumed 30%
-See https://github.com/NREL/SAM/pull/1807 for context of this and what was added in patch 2
-See https://github.com/NREL/ssc/pull/1218 for ssc

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by cpaulgilman — COMMENTED** [review]
@mjprilliman Should this new input variable in the UI be named `tidal_turbine_target_cf` with the label "Target capacity factor" to avoid confusion with the capacity factor output?

**Comment by mjprilliman** [comment]
> @mjprilliman Should this new input variable in the UI be named `tidal_turbine_target_cf` with the label "Target capacity factor" to avoid confusion with the capacity factor output?

Yes that's a great point. I will clean this up.

**Review by cpaulgilman — APPROVED** [review]
Variable name and label changes look good.

**Comment by cpaulgilman** [comment]
@mjprilliman Could you add a short description here of how the target capacity factor input works that I can use as a basis for Help documentation?

**Comment by cpaulgilman** [comment]
> @mjprilliman Could you add a short description here of how the target capacity factor input works that I can use as a basis for Help documentation?

Thank you for emailing the description.

**Pull request merged**
