### PR TITLE
Fix first issue with lk "set" function in #458

### PR DESCRIPTION
**Pull request by sjanzou**

### CODE REVIEW

**Review by cpaulgilman — APPROVED** [review]
Looks good. I tested the small numbers LK example and the ME Wave LK script.

**Comment by mjprilliman** [comment]
image

Did this affect the decimal reporting in calculated variables?

**Comment by sjanzou** [comment]
> image
> 
> Did this affect the decimal reporting in calculated variables?

The wex fix to the wxNumeric control so that more precision can be sent through ssc_exec caused this issue.

**Comment by cpaulgilman** [comment]
> > image
> > Did this affect the decimal reporting in calculated variables?
> 
> The wex fix to the wxNumeric control so that more precision can be sent through ssc_exec caused this issue.

Is a solution to change the definition of the "Generic" format so it displays up to four decimal places?

**Comment by sjanzou** [comment]
> > > image
> > > Did this affect the decimal reporting in calculated variables?
> > 
> > 
> > The wex fix to the wxNumeric control so that more precision can be sent through ssc_exec caused this issue.
> 
> Is a solution to change the definition of the "Generic" format so it displays up to four decimal places?

Possibly, then we still need another format for the inputs for which we want to keep as much precsision as possible (e.g. user entered 6 paramter modules). Doubles have about 16 digits of precision according to most sources.

**Comment by cpaulgilman** [comment]
> > > > image
> > > > Did this affect the decimal reporting in calculated variables?
> > > 
> > > 
> > > The wex fix to the wxNumeric control so that more precision can be sent through ssc_exec caused this issue.
> > 
> > 
> > Is a solution to change the definition of the "Generic" format so it displays up to four decimal places?
> 
> Possibly, then we still need another format for the inputs for which we want to keep as much precsision as possible (e.g. user entered 6 paramter modules). Doubles have about 16 digits of precision according to most sources.

Otherwise, do we write a utility to convert all variables with "Generic" format to "Fixed" with 3 or 4 decimals, and then manually change the ones that need to be Generic for maximum precision?

**Comment by sjanzou** [comment]
> > > > > image
> > > > > Did this affect the decimal reporting in calculated variables?
> > > > 
> > > > 
> > > > The wex fix to the wxNumeric control so that more precision can be sent through ssc_exec caused this issue.
> > > 
> > > 
> > > Is a solution to change the definition of the "Generic" format so it displays up to four decimal places?
> > 
> > 
> > Possibly, then we still need another format for the inputs for which we want to keep as much precsision as possible (e.g. user entered 6 paramter modules). Doubles have about 16 digits of precision according to most sources.
> 
> Otherwise, do we write a utility to convert all variables with "Generic" format to "Fixed" with 3 or 4 decimals, and then manually change the ones that need to be Generic for maximum precision?

Hmmm... maybe we can start a poll? I think some may not like 4 fixed digits for many of the large calculated values... I think the maximum precision is a much smaller subset and thaose can be updated manually during loc down...

**Comment by cpaulgilman** [comment]
> > > > > > image
> > > > > > Did this affect the decimal reporting in calculated variables?
> > > > > 
> > > > > 
> > > > > The wex fix to the wxNumeric control so that more precision can be sent through ssc_exec caused this issue.
> > > > 
> > > > 
> > > > Is a solution to change the definition of the "Generic" format so it displays up to four decimal places?
> > > 
> > > 
> > > Possibly, then we still need another format for the inputs for which we want to keep as much precsision as possible (e.g. user entered 6 paramter modules). Doubles have about 16 digits of precision according to most sources.
> > 
> > 
> > Otherwise, do we write a utility to convert all variables with "Generic" format to "Fixed" with 3 or 4 decimals, and then manually change the ones that need to be Generic for maximum precision?
> 
> Hmmm... maybe we can start a poll? I think some may not like 4 fixed digits for many of the large calculated values... I think the maximum precision is a much smaller subset and thaose can be updated manually during loc down...

True, would 3 be better? Some of the inputs already have a fixed format. If we made this change, I think we could plan to clean up number formats over time.

**Pull request merged**
