### PR TITLE
PV Default updates

### LINKED ISSUE #792: RC PV Defaults Need Updating
Some PV default values in the release candidate need to be updated, for example PV-SO system is fixed tilt. Matt said he'd go through and take a look and commit updated defaults to develop this week.

### PR DESCRIPTION
**Pull request by mjprilliman**
## Description

Update default values for PV Systems based on latest ATB spreadsheet. Utility-scale PV was modeled as single axis tracking system in the ATB so the default was modified for PV and PVWatts. The DC - AC ratios were adjusted in PVWatts to the latest benchmark report value of 1.15 (from 1.2). Test results were updated with new default values. 

Fixes #792 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by janinefreeman** [comment]
Reviewing these now, you may already be planning to build SAM_api before merging but I think this is one of those times where we need to if I understood correctly.

**Comment by dguittet** [comment]
Thanks for the heads up--I can wait!

From: Janine ***@***.***>
Date: Tuesday, November 23, 2021 at 9:16 AM
To: NREL/SAM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [NREL/SAM] PV Default updates (PR #793)

CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Reviewing these now, you may already be planning to build SAM_api before merging but I think this is one of those times where we need to if I understood correctly.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNREL%2FSAM%2Fpull%2F793%23issuecomment-976789210&data=04%7C01%7Cdarice.guittet%40nrel.gov%7C7d6deb5a965e4a6176f908d9ae9ca0e0%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637732810025614124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5%2Bad8az%2BSPP3up6ZiUBJU0xD%2BeTkH3EjUiHOkKBukzY%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHAGXWF3BCWJDTKZIJQKPGLUNO46NANCNFSM5ISEAPYQ&data=04%7C01%7Cdarice.guittet%40nrel.gov%7C7d6deb5a965e4a6176f908d9ae9ca0e0%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637732810025624080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ByLQyEQGhwTOFtFfBOb1K%2FFqxgEuo4nu6sT7UuxqVoI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdarice.guittet%40nrel.gov%7C7d6deb5a965e4a6176f908d9ae9ca0e0%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637732810025634040%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eLBXYuPvww%2BrRtghjpXKnIjI5kIHRpaEUwhgHmwiPqM%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdarice.guittet%40nrel.gov%7C7d6deb5a965e4a6176f908d9ae9ca0e0%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637732810025634040%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KTW0D3A9a9IBQhM2aPLnJmT4wkRuwPYbfnbyWBsExuk%3D&reserved=0>.

**Comment by mjprilliman** [comment]
@janinefreeman I just pushed a commit for wind system size and capex updates. You had a separate testing item for wind costs outside of ATB updates, but I updated these values using ATB utility wind and offshore wind values so not sure if this is what was expected. Happy to revert the commit if not. @brtietz already updated the capacity O&M values to match that of the ATB.

**Comment by janinefreeman** [comment]
That sounds perfect. As more defaults align with the ATB, we have fewer that need to be updated separately :)

**Review by janinefreeman — COMMENTED** [review]
Pending updates to test script results, I would say this looks reasonable so far. @mjprilliman I'm done with my updates, let me know when you'd like me to review again

**Review by dguittet — APPROVED** [review]

**Comment by mjprilliman** [comment]
Changes to make the ppa prices the default for electricity purchases caused the generic battery and standalone battery configs to fail because they were still on 'Specify IRR target' mode. Determining reasonable PPA prices and re-running the test script before merging.

**Pull request merged**
