### PR TITLE
Defaults updates financials biopower o&m

### PR DESCRIPTION
**Pull request by brtietz**
Update:

- O&M to remove values we've been double counting  (reference: https://github.com/NREL/SAM-documentation/blob/master/Defaults%20References%20and%20Tools/Fall%202021/O%26M%20Updates%202021.12.02.xlsx)
- Interest rates to match ATB (Fixes https://github.com/NREL/SAM/issues/553)
- PPA prices for PV front of meter cases to account for decreased interest rates (reference: https://emp.lbl.gov/pv-ppa-prices)
- Reduce inverter costs in reserve accounts (reference: https://www.nrel.gov/docs/fy19osti/73822.pdf)
- Apply inflation to biopower cost inputs

Run the test script to see the results with these new defaults.

### CODE REVIEW

**Comment by cpaulgilman** [comment]
A few issues:

* PVWatts / Single Owner NPV is negative. NPV is very sensitive to PPA price in the 4-5 cent/kWh range:

image

* For PV configurations, the default "Annual land lease cost" `ui_land_lease` of $100/yr and "Land lease escalation rate" `om_land_lease_escal` of 1%/yr from the Operating Costs page appear to be left over test values. I think these should both be set to zero unless we have a source for those values. This would increase the default PV / Single Owner NPV by about 10%. The[ ATB documentation](https://atb.nrel.gov/electricity/2021/utility-scale_pv#95JQPNCX) mentions land lease is included in O&M cost and I could not find it broken out as a separate cost in the LBL report it cites.

* Although this is not necessary, it would be nice for the default IRR target and IRR target year to match the results for "Specify PPA price" mode so that if a user switches from Specify PPA price to Specify IRR target without changing any other inputs, they get the same results. This would be tedious to do because it requires running a simulation for all configurations -- something that could be done by LK script.

* For all FOM financial configs, retail rate inputs on Electricity Purchases page should have the following values in case user switches from PPA to retail rates.

    ```
   ur_monthly_fixed_charge = 0
    ur_ec_tou_mat = [ [ 1, 1, 1e+38, 0, 0.045, 0 ] ]
    ur_dc_enable = 0
    ur_dc_flat_mat = [ [ 0, 1, 1e+38, 0 ], [ 1, 1, 1e+38, 0 ], [ 2, 1, 1e+38, 0 ], [ 3, 1, 1e+38, 0 ], [ 4, 1, 1e+38, 0 ], [ 5, 1, 1e+38, 0 ], [ 6, 1, 1e+38, 0 ], [ 7, 1, 1e+38, 0 ], [ 8, 1, 1e+38, 0 ], [ 9, 1, 1e+38, 0 ], [ 10, 1, 1e+38, 0 ], [ 11, 1, 1e+38, 0 ] ]
    ur_dc_tou_mat = [ [ 1, 1, 1e+38, 0 ] ]
    ```

* Power Tower PPA price input of $0.13/kWh seems high. Calculated PPA price in SAM 2020.11.29 is $0.1032 with end of project IRR of 12.82% (which also seems high to me). Consult with CSP folks to see what default PPA prices / IRR they would like to see for CSP configs.

**Comment by mjprilliman** [comment]
> A few issues:
> 
> * PVWatts / Single Owner NPV is negative. NPV is very sensitive to PPA price in the 4-5 cent/kWh range:
> 
> image
> 
> * For PV configurations, the default "Annual land lease cost" `ui_land_lease` of $100/yr and "Land lease escalation rate" `om_land_lease_escal` of 1%/yr from the Operating Costs page appear to be left over test values. I think these should both be set to zero unless we have a source for those values. This would increase the default PV / Single Owner NPV by about 10%. The[ ATB documentation](https://atb.nrel.gov/electricity/2021/utility-scale_pv#95JQPNCX) mentions land lease is included in O&M cost and I could not find it broken out as a separate cost in the LBL report it cites.
> * Although this is not necessary, it would be nice for the default IRR target and IRR target year to match the results for "Specify PPA price" mode so that if a user switches from Specify PPA price to Specify IRR target without changing any other inputs, they get the same results. This would be tedious to do because it requires running a simulation for all configurations -- something that could be done by LK script.
> * For all FOM financial configs, retail rate inputs on Electricity Purchases page should have the following values in case user switches from PPA to retail rates.
>   ```
>   ur_monthly_fixed_charge = 0
>   ur_ec_tou_mat = [ [ 1, 1, 1e+38, 0, 0.045, 0 ] ]
>   ur_dc_enable = 0
>   ur_dc_flat_mat = [ [ 0, 1, 1e+38, 0 ], [ 1, 1, 1e+38, 0 ], [ 2, 1, 1e+38, 0 ], [ 3, 1, 1e+38, 0 ], [ 4, 1, 1e+38, 0 ], [ 5, 1, 1e+38, 0 ], [ 6, 1, 1e+38, 0 ], [ 7, 1, 1e+38, 0 ], [ 8, 1, 1e+38, 0 ], [ 9, 1, 1e+38, 0 ], [ 10, 1, 1e+38, 0 ], [ 11, 1, 1e+38, 0 ] ]
>   ur_dc_tou_mat = [ [ 1, 1, 1e+38, 0 ] ]
>   ```
> * Power Tower PPA price input of $0.13/kWh seems high. Calculated PPA price in SAM 2020.11.29 is $0.1032 with end of project IRR of 12.82% (which also seems high to me). Consult with CSP folks to see what default PPA prices / IRR they would like to see for CSP configs.

I pushed the land lease fix to this branch. 

I addressed some of the utility rate issues in https://github.com/NREL/SAM/pull/790 but need to upate theur_ec_tou_mat and the ur_dc_tou_mat

**Review by cpaulgilman — APPROVED** [review]

**Comment by mjprilliman** [comment]
@cpaulgilman The calculated PPA price for PVWatts - Single Owner with the updated utility rates and a IRR target of 11% is 4.96 cents/kWh. Should we use that?

**Comment by cpaulgilman** [comment]
Would be good to have something close to the Detailed PV case -- if there's PPA price for a lower IRR that results in a positive NPV that would be good. Nitpicking here, so I wouldn't hold this up for that.

**Comment by brtietz** [comment]
My default value for utility scale systems of $13/kW-yr does not include land payments. Should I increase that based on https://github.com/NREL/SAM-documentation/blob/master/Defaults%20References%20and%20Tools/Fall%202021/Copy%20of%20OandM%20TabularForm_Graphic.xlsx? I think land prep on the installation costs should remain the same.

**Comment by brtietz** [comment]
If I increase the fixed O&M to $15/kW-yr (to account for land lease) and the PPA price to $0.048/kWh, I get a positive NPV for both Detailed PV-Single owner and PVWatts-Single owner.

**Pull request merged**
