### PR TITLE
Fixed battery sizing equations to reference computed bank power rather than desired bank power and capacity

### PR DESCRIPTION
**Pull request by mjprilliman**
-Sets correct battery bank capacity and bank power basis for maximum discharge and charge calculations on both AC and DC connected systems for AC and DC battery sizing options
-Changes * dc_ac efficiency to / ac_dc efficiency for Bank power maximum charge AC calculations when AC connected

### CODE REVIEW

**Review by cpaulgilman — APPROVED** [review]

**Comment by cpaulgilman** [comment]
Here are a set of diagrams and screenshots showing how the calculations are expected to work:

[battery-power-calculations.zip](https://github.com/NREL/SAM/files/6133209/battery-power-calculations.zip)

**Comment by cpaulgilman** [comment]
@dguittet If you have a chance, could you review this pull request? I'd like to have this merged into patch before I start my work reorganizing the battery UI inputs. 

Thanks!
Paul.

**Review by dguittet — APPROVED** [review]

**Comment by dguittet** [comment]
Looks good! Sorry for the delay.

**Comment by mjprilliman** [comment]
See #580 for merged changes, this branch has messed up root branches. Closing this PR

**Pull request closed without merging**
