### PR TITLE
Update Cambium to 2023 and Handle Changes in API Response

### LINKED ISSUE #1786: Out-of-date Cambium metadata variable prevents downloads from working
When SAM downloads pricing data from the Cambium API it stores metadata from the API in a variable to populate the input options. As the Cambium API is updated over time the metadata changes. If you try to download Cambium data after the API changes, the downloads fail with an API error message.

See https://sam.nrel.gov/forum/forum-general/4649 for details and a workaround solution.

To fix the problem, SAM should display a message if the stored metadata is different from metadata from the API so that the user knows about the changes.

### PR DESCRIPTION
**Pull request by cpaulgilman**
## Description

* Updates from Cambium 2022 to Cambium 2023.

* Fixes #1786

Goes with https://github.com/NREL/SAM-private/pull/113

"Cambium API Parameters" inputs on the Revenue page for Merchant Plant configurations uses list boxes to display options for downloading price data from Cambium API. These options are populated by downloading metadata from the API (in a step before downloading the actual price data). The metadata API has changed over time, so old SAM files may have options that are no longer available, which causes the API to return an error when the user clicks the Download button, preventing Cambium downloads from working.

This PR modifes the Cambium download UI callback script to compare the inputs in SAM with the latest API metadata, and refreshes the SAM inputs if the metadata is different from the inputs It also displays messages notifying the user of which inputs need to be updated.

See https://github.com/NREL/SAM/issues/1786.

To test:

1. Download the .sam file from the forum post originally reporting this issue: https://sam.nrel.gov/forum/attachment/2016?download=1
2. Open the file, and go to the Revenue page for any of the cases with a Merchant Plant configuration.
3. Click **Download to Energy Market**.

SAM should prompt you to update the metadata and then download price data without an API error.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change modifies variables in existing compute modules. Please see [Checking for PySAM Incompatible API Changes](https://github.com/NREL/SAM/wiki/Checking-for-PySAM-Incompatible-API-Changes).

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by brtietz — APPROVED** [review]
This works great! Very clear error messages. I also tested it with the 2022->2023 cambium version, and it correctly updates to the new ISO regions (not states)

Do you want to update the url in webaips.conf in this PR or later? The 2023 API is `https://scenarioviewer.nrel.gov/api/project/detail/?uuid=0f92fe57-3365-428a-8fe8-0afc326b3b43`

**Comment by cpaulgilman** [comment]
> Do you want to update the url in webaips.conf in this PR or later? The 2023 API is `https://scenarioviewer.nrel.gov/api/project/detail/?uuid=0f92fe57-3365-428a-8fe8-0afc326b3b43`

Yes. I'll do that. I was looking for that UUID -- where did you find it?

**Comment by brtietz** [comment]
> > Do you want to update the url in webaips.conf in this PR or later? The 2023 API is `https://scenarioviewer.nrel.gov/api/project/detail/?uuid=0f92fe57-3365-428a-8fe8-0afc326b3b43`
> 
> Yes. I'll do that. I was looking for that UUID -- where did you find it?

Luckily, the UUID in API is the same as the project field in the GUI from https://scenarioviewer.nrel.gov/

**Comment by cpaulgilman** [comment]
> > > Do you want to update the url in webaips.conf in this PR or later? The 2023 API is `https://scenarioviewer.nrel.gov/api/project/detail/?uuid=0f92fe57-3365-428a-8fe8-0afc326b3b43`
> > 
> > 
> > Yes. I'll do that. I was looking for that UUID -- where did you find it?
> 
> Luckily, the UUID in API is the same as the project field in the GUI from https://scenarioviewer.nrel.gov/

Ah! Nice find. Thanks.

**Pull request merged**
