### PR TITLE
Fix SAM issue #1417, tested macOS 14.0

### PR DESCRIPTION
**Pull request by sjanzou**
https://github.com/NREL/SAM/issues/1417

Note that stochastic simulations not currently available or supported for hybrid configurations.

### CODE REVIEW

**Review by cpaulgilman — COMMENTED** [review]
I'm still running into the message for stochastic and uncertainty simulations:

Screenshot 2023-10-19 at 4 46 02 PM


Screenshot 2023-10-19 at 4 44 19 PM

**Comment by sjanzou** [comment]
> I'm still running into the message for stochastic and uncertainty simulations on a MacBook Air M1 2020 macOS 13.4.1:
> 
> Screenshot 2023-10-19 at 4 46 02 PM Screenshot 2023-10-19 at 4 44 19 PM

Hmmm... using the file from #1417, I get the stochastic simulations running as:
image

with results
image

@cpaulgilman , can you please attach the failing project file and what macOS version and architecture you are testing on?

**Comment by sjanzou** [comment]
The issue appears to be in the final distributed app... when testing from XCode, the branch builds and runs and generates samples without issue. However, when built and the installed on a system, the error remains. 

Checking signing of lhs.bin

**Comment by sjanzou** [comment]
Replaced by https://github.com/NREL/SAM/pull/1782

**Pull request closed without merging**
