### PR TITLE
Fix default type per issue #1093

### PR DESCRIPTION
**Pull request by sjanzou**

### CODE REVIEW

**Comment by sjanzou** [comment]
@brtietz , @mjprilliman , @cpaulgilman please approve and merge this pull request before making any additional default updates so we can moved to JSON defaults per pull request https://github.com/NREL/SAM/pull/1096

**Review by brtietz — COMMENTED** [review]
The defaults changes look good - but why would LCOE change? I'd be a little more comfortable if we get whatever defaults changes done due to SSC changes on develop before merging this, so we can be more confident in whatever outputs changes the tests are telling us about.

**Comment by sjanzou** [comment]
> The defaults changes look good - but why would LCOE change? I'd be a little more comfortable if we get whatever defaults changes done due to SSC changes on develop before merging this, so we can be more confident in whatever outputs changes the tests are telling us about.

What LCOE changes? These match with PR1091 merged into develop? The only change here was dues to incorrect type specification for the inputs of checked boxes - several were specified as arrays and the JSONDefaults branch does additional type checking as defaults are read in. So, the arrays read in as numbers fail…

**Comment by brtietz** [comment]
> > The defaults changes look good - but why would LCOE change? I'd be a little more comfortable if we get whatever defaults changes done due to SSC changes on develop before merging this, so we can be more confident in whatever outputs changes the tests are telling us about.
> 
> What LCOE changes? These match with PR1091 merged into develop? The only change here was dues to incorrect type specification for the inputs of checked boxes - several were specified as arrays and the JSONDefaults branch does additional type checking as defaults are read in. So, the arrays read in as numbers fail…

There is a two cent change in LCOE in the test results committed to this PR:

image

**Comment by sjanzou** [comment]
> > > The defaults changes look good - but why would LCOE change? I'd be a little more comfortable if we get whatever defaults changes done due to SSC changes on develop before merging this, so we can be more confident in whatever outputs changes the tests are telling us about.
> > 
> > 
> > What LCOE changes? These match with PR1091 merged into develop? The only change here was dues to incorrect type specification for the inputs of checked boxes - several were specified as arrays and the JSONDefaults branch does additional type checking as defaults are read in. So, the arrays read in as numbers fail…
> 
> There is a two cent change in LCOE in the test results for residential PV committed to this PR, smaller in other configurations:
> 
> image

@brtietz , those values are correct. The issue was that the test_results.csv originally committed in the pull request were out of date. I updated the defaults from the latest develop branch after this pull request was updated, so I the pull request was not comparing the the latest develop branch. Specifically, check the test_results.csv file currently in develop after pr 1091 was merged.

**Review by cpaulgilman — DISMISSED** [review]

**Comment by brtietz** [comment]
> > > > The defaults changes look good - but why would LCOE change? I'd be a little more comfortable if we get whatever defaults changes done due to SSC changes on develop before merging this, so we can be more confident in whatever outputs changes the tests are telling us about.
> > > 
> > > 
> > > What LCOE changes? These match with PR1091 merged into develop? The only change here was dues to incorrect type specification for the inputs of checked boxes - several were specified as arrays and the JSONDefaults branch does additional type checking as defaults are read in. So, the arrays read in as numbers fail…
> > 
> > 
> > There is a two cent change in LCOE in the test results for residential PV committed to this PR, smaller in other configurations:
> > image
> 
> @brtietz , those values are correct. The issue was that the test_results.csv originally committed in the pull request were out of date. I updated the defaults from the latest develop branch after this pull request was updated, so I the pull request was not comparing the the latest develop branch. Specifically, check the test_results.csv file currently in develop after pr 1091 was merged.

Got it. Merging develop into this branch and resolving the conflicts is strongly preferred over generating a new file, which can generate a lot of confusion ;)

**Comment by sjanzou** [comment]
> 

@brtietz, agreed... following conventional wisdom and merging in develop and resubmitting,,,

**Comment by sjanzou** [comment]
Redone with updates from Develop and ready to merge

**Review by brtietz — APPROVED** [review]

**Pull request merged**
