### PR TITLE
Fix cf energy sales

### PR DESCRIPTION
**Pull request by brtietz**
Cashflow.lk changes to go with https://github.com/NREL/ssc/pull/750

Additional changes may be needed for "send to excel with equations" please advise

### CODE REVIEW

**Comment by cpaulgilman** [comment]
@brtietz This should be branched off of Patch instead of Develop. Similar to SSC, my om_cost_inputs branch has other fixes related to cash flow, so I would like to merge fix_cf_energy_sales into om_cost_inputs and then into Patch if that's OK by you.

**Comment by brtietz** [comment]
@cpaulgilman looks like it was just a target branch issue in the pull request - I've fixed that (I wonder if we should adjust that default during patch season). Yes, feel free to do that merging route.

**Comment by cpaulgilman** [comment]
Send-to-Excel with equations will be handled when I address https://github.com/NREL/SAM/issues/694

**Comment by brtietz** [comment]
Included in https://github.com/NREL/SAM/pull/927 - closing this PR

**Pull request closed without merging**
