### PR TITLE
Fall 2022 defaults updates: part 1

### PR DESCRIPTION
**Pull request by brtietz**
## Description

Defaults update for Fall 2022. Update includes:

* Updated PV, Battery, and Wind CAPEX, O&M numbers, and system sizes
* Updated incentives for all technologies based on IRA "base case"

This is part 1.

Once we approve these costs, I can update revenue to correct issues with IRR or NPV as possible
(ex: cases that didn't have negative NPV but now do due to increased costs). (target 11/14)

Part 3 will include updating the calculated values in the defaults and export for PySAM (target 11/15)

References available in: https://github.com/NREL/SAM-documentation/tree/master/Defaults%20References%20and%20Tools/Fall%202022

When a $/kW value was available, it was used with inflation to 2022 dollars

When only a $ value was available (often the case for batteries) I attempted to maintain fidelity with the ATB spreadsheet
projections first, and the benchmark second, targeting the total dollar amount in the benchmark.

### CODE REVIEW

**Review by tyneises — APPROVED** [review]
Part 1 looks fine to me, although the tests seem to be hanging?

I added some molten salt power tower technology default changes.

**Review by mjprilliman — COMMENTED** [review]
-Utility PV O&M in Ramasamy 2022 is 16.42 '$'/kWdC (2021$), SAM number is 15?
-Not really sure of the best procedure to review numbers for battery and wind defaults

**Comment by mjprilliman** [comment]
Think test issues are a result of #1254. Working on a fix

**Comment by mjprilliman** [comment]
There's something funny going on with the defaults. In Standalone battery - Residential, for example: 

image

image

image

image

**Comment by brtietz** [comment]
> There's something funny going on with the defaults. In Standalone battery - Residential, for example:
> 
> image
> 
> image
> 
> image
> 
> image
> 
> I found these "3", "Default", and "Numeric" default values in Standalone Battery for Residential, Commercial, and Single Owner

Odd, I don't see those locally, or on GitHub: https://github.com/NREL/SAM/blob/78f6b4aa6379355202bb95f2087d775aecc376e7/deploy/runtime/defaults/Standalone%20Battery_Residential.json

**Comment by mjprilliman** [comment]
> > There's something funny going on with the defaults. In Standalone battery - Residential, for example:
> > image
> > image
> > image
> > image
> > I found these "3", "Default", and "Numeric" default values in Standalone Battery for Residential, Commercial, and Single Owner
> 
> Odd, I don't see those locally, or on GitHub: https://github.com/NREL/SAM/blob/78f6b4aa6379355202bb95f2087d775aecc376e7/deploy/runtime/defaults/Standalone%20Battery_Residential.json

Right sorry that was not clear. Those variables were being written to the default file on standalone battery case load based on the reading of the Standalone Battery Cost UI form, which at least for me was missing lots of information (https://github.com/NREL/SAM/pull/1248/commits/c013a59dff7362230509e827427c5cda987012dc) and was therefore passing the wrong variables to the defaults file. So callback errors were prompted on Standalone Battery case startup and the test script was being interrupted.

**Comment by brtietz** [comment]
> Right sorry that was not clear. Those variables were being written to the default file on standalone battery case load based on the reading of the Standalone Battery Cost UI form, which at least for me was missing lots of information ([c013a59](https://github.com/NREL/SAM/commit/c013a59dff7362230509e827427c5cda987012dc)) and was therefore passing the wrong variables to the defaults file. So callback errors were prompted on Standalone Battery case startup and the test script was being interrupted.

Ah, ok, thanks for fixing it!

**Comment by sjanzou** [comment]
> > > There's something funny going on with the defaults. In Standalone battery - Residential, for example:
> > > image
> > > image
> > > image
> > > image
> > > I found these "3", "Default", and "Numeric" default values in Standalone Battery for Residential, Commercial, and Single Owner
> > 
> > 
> > Odd, I don't see those locally, or on GitHub: https://github.com/NREL/SAM/blob/78f6b4aa6379355202bb95f2087d775aecc376e7/deploy/runtime/defaults/Standalone%20Battery_Residential.json
> 
> Right sorry that was not clear. Those variables were being written to the default file on standalone battery case load based on the reading of the Standalone Battery Cost UI form, which at least for me was missing lots of information ([c013a59](https://github.com/NREL/SAM/commit/c013a59dff7362230509e827427c5cda987012dc)) and was therefore passing the wrong variables to the defaults file. So callback errors were prompted on Standalone Battery case startup and the test script was being interrupted.

Let me know if any more of these anomalies appear... seems like the UI forms are still being corrupted on some of the automerges...

**Pull request merged**
