### PR TITLE
Add "Copy table >" functionality to P50/P90 

### PR DESCRIPTION
**Pull request by sjanzou**

### CODE REVIEW

**Comment by sjanzou** [comment]
SAM project file and P50/P90 weather files for testing  
[SAM_141.zip](https://github.com/NREL/SAM/files/7520353/SAM_141.zip)


with results
image

**Review by mjprilliman — APPROVED** [review]
Your example worked well for me. That's a very useful feature!

**Comment by cpaulgilman** [comment]
This works well, but I would recommend changing the label to "Copy table to clipboard" or "Copy to clipboard" and removing the ">" because it suggests that a context menu or other window will open.

**Comment by sjanzou** [comment]
Update button label per comments
image

**Pull request merged**
