### PR TITLE
Marine CBS UI enhancements

### LINKED ISSUE #389: Marine Energy model CBS integration
Implement ME cost breakdown structure for detailed cost inputs to the wave and tidal models.

### LINKED ISSUE #390: Marine energy summary page enhancements
Add requested output metrics to ME wave and tidal model summary pages. Allow for more than one table on the summary page, with tables being able to have more than 2 columns. Add sector plotting to autographs.lk. 

This work is in marine_cost_UI branch for SAM, ssc, and wex.

### PR DESCRIPTION
**Pull request by mjprilliman**
-Designed 4 cost pages with options for varying level of cost definitions for various aspects of Marine Energy Converter projects (both wave and tidal)
-Summary page enhancements that allow for multiple tables, multiple columns per table
-Linked to ssc pull request with same branch name. 
-Also includes wex changes

-Closes #389 
-Closes #390

### CODE REVIEW

**Comment by mjprilliman** [comment]
@cpaulgilman Would it be possible to change the documentation to reflect changing labels for the itemized costs? Cost breakdown is more consistent with the Marine Energy terminology so far. If that is more confusing that way I can revert. 

image

image

**Comment by cpaulgilman** [comment]
@mjprilliman Yes. I'm happy to make those changes. I'll do that work in this branch so you can review. If that causes conflicts with Help files when you merge this branch into Develop, feel free to overwrite the ones in Develop. I will build a new Help system for the Develop branch right before we build the beta release version.

One question: Your screenshots above use "cost breakdown" but what I see in the version I built this morning is "itemized costs". Either is fine, I just want to make sure use the correct terms in Help.

**Comment by mjprilliman** [comment]
@cpaulgilman I forgot to push my changes last night. Just pushed now. Cost breakdown is what I am going with now

**Comment by cpaulgilman** [comment]
Help revisions done in https://github.com/NREL/SAM/commit/c89fa6f6b78175afaa0cff18d700ec7b7224b881.

**Comment by mjprilliman** [comment]
@sjanzou @cpaulgilman merging this in for the beta.

**Pull request merged**
