### PR TITLE
UI for Critical Loads and Grid Outage for all BTM Storage Configs

### PR DESCRIPTION
**Pull request by cpaulgilman**
Goes with https://github.com/NREL/ssc/pull/618

* Add Grid Outage UI form with grid_outage input

* Reorganize Electric Load page for better usability

* Improve labeling of critical load inputs, including option for time series resiliency calcs

* UI conditional messaging to ensure grid outage is not enable without critical load, and check fuel cell configs for enabled battery

### CODE REVIEW

**Comment by cpaulgilman** [comment]
When the user specifies a critical load with no grid outage, what does SAM do when run_resiliency_calcs = 0?

**Comment by cpaulgilman** [comment]
<table>
<tbody>
<tr>
<td>critical_load</td>
<td>grid_outage</td>
<td>run_resiliency_calcs</td>
<td>Result</td>
<td>UI Behavior</td>
</tr>
<tr>
<td>0</td>
<td>0</td>
<td>0</td>
<td>Normal SAM operation</td>
<td>Disable run_resiliency_calcs and set to zero.</td>
</tr>
<tr>
<td>0</td>
<td>0</td>
<td>1</td>
<td>Invalid, need critical load.</td>
<td>Not possible to get to this state in UI.</td>
</tr>
<tr>
<td>0</td>
<td>1</td>
<td>0</td>
<td>Invalid, need critical load.</td>
<td>Disable run_resiliency_calcs and set to zero.</td>
</tr>
<tr>
<td>0</td>
<td>1</td>
<td>1</td>
<td>Invalid, need critical load.</td>
<td>Disable run_resiliency_calcs and set to zero.</td>
</tr>
<tr>
<td>1</td>
<td>0</td>
<td>0</td>
<td>Critical load doesn't do anything.</td>
<td>Display a UI message to either specify a grid outage and/or set run_resiliency_calcs to 1.</td>
</tr>
<tr>
<td>1</td>
<td>0</td>
<td>1</td>
<td>Equivalent to SAM 2020.11.29: Outage is hypothetical, code starts outage in every time step and sees how long battery survives. Tells you how long could you survive an outage. Does not affect battery SOC.</td>
</tr>
<tr>
<td>1</td>
<td>1</td>
<td>0</td>
<td>Results only for outage time steps. Affects battery SOC.</td>
</tr>
<tr>
<td>1</td>
<td>1</td>
<td>1</td>
<td>Models a real outage that battery has to recover from and a hypothetical one. The resiliency metrics will run for every timestep with a hypothetical outage. During the real outage, they should match the behavior during that outage (in terms of hours of survival). Both during and after the outage, we'll see how many additional hours the system could have survived based on the final SOC.</td>
</tr>
</tbody>
</table>

**Review by brtietz — APPROVED** [review]
Looks good! Need to wait to merge until SSC code is ready. Hopefully this will be possible with the connect_outage_vars_to_powerflow branch.

**Review by sjanzou — APPROVED** [review]
All my tests are running fine now... first sanity check has passed! Ready to merge.

**Pull request merged**
