### PR TITLE
Marine energy metrics in ssc var_tables

### LINKED ISSUE #769: Some metric table outputs are not in compute modules and are not available in code generation
### Describe the bug

Some metric table outputs are not in compute modules and are not available in code generation

### To Reproduce

1. run ME Wave FCR configuration 
2. generate lk for SDK Tool
3. Run in SDKTool
4. Some metrics are reported as <NULL>

### Expected behavior

Expect only values that appear in Data Tables to be available for metrics

### Screenshots

image

image

image

### Operating System and Version

 - OS: [Windows, macOS, Linux]
 - Version [e.g. SAM 2020.2.29 r3]

### Additional context

Project file to reproduce using first case and referenced in #558 and #685
[test_SAM_558.zip](https://github.com/NREL/SAM/files/7538624/test_SAM_558.zip)

### PR DESCRIPTION
**Pull request by mjprilliman**
## Description
This PR corrects marine energy outputs that were only calculated in the UI by moving the calculations and the variable definitions to the ssc compute module mhk_wave. This allows the metric tables to be reported correctly in the SDK tool. 

See corresponding PR in ssc. 

Fixes #769 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by sjanzou — CHANGES_REQUESTED** [review]
One code generator bug was encountered and fixed in the SAM me_metrics_updates branch.
As mentioned in ssc pull request 670, could you please check the issue encountered on a clean installation of SAM when creating a ME Wave case:
image

**Comment by mjprilliman** [comment]
> One code generator bug was encountered and fixed in the SAM me_metrics_updates branch. As mentioned in ssc pull request 670, could you please check the issue encountered on a clean installation of SAM when creating a ME Wave case: image

I believe this is a issue that occurs when writing the wave resource library csv file to the User's local data for the first time. We've run into this issue in the past and restarting SAM seems to fix the issue. I do not believe this issue shows up in the built releases but I will test.

**Comment by mjprilliman** [comment]
@sjanzou Do you get that error each time you open a wave case or only on the first load? There were some format changes to the WaveResourceTSData.csv file that is stored on the local drive that may cause issues on first load before correcting themselves. You can use the browse(userlocaldatadir()); command in the LK scripting tool to see the file. Neither Brian nor I have been able to replicate this on develop or the latest Beta releases.

**Comment by mjprilliman** [comment]
@sjanzou @cpaulgilman I probably missed a step somewhere but there is supposed to be a wave_resource_ts folder in deploy that has not made it's way into the files of either of the most recent betas. 

image

How do I correct this?

**Comment by sjanzou** [comment]
Working on linux and updated on macOS to copy over wave_resource_ts to
build processes.

**Comment by sjanzou** [comment]
Updated for all build processes to include wave_resource_ts in
installations.

**Pull request merged**
