### PR TITLE
Fix bug in billing demand yr 0 peaks

### PR DESCRIPTION
**Pull request by brtietz**
When merging https://github.com/NREL/SAM/pull/728, I missed the fact that setting chk_update_peaks to 1 prevented the callback that set the year 0 peaks from running. Add a check to that variable immediately upon enabling billing demand calcs, so they values are always present.

### CODE REVIEW

**Comment by brtietz** [comment]
Failure matches version of develop used to create this branch. Develop was fixed here: https://github.com/NREL/SAM/runs/4182767103. I can merge in develop and re-run if desired, but refraining for now to save Travis credits.

**Review by cpaulgilman — CHANGES_REQUESTED** [review]
If Use Monthly Peaks is checked, the monthly peaks array should be updated on_load so that if you change the load data the peaks are updated. For example:

1. On Electricity Rates page, check **Use monthly peaks from Year 1...**.
2. On Electric Load page, change **Electric load scaling factor** to 2.
3. Go back to Electricity Rates page and clear Use Monthly Peaks checkbox and click **Edit values* to see values.

**Comment by brtietz** [comment]
@cpaulgilman Good catch! In that case, do we want the yes/no dialogue box to pop up, or should the overwrite happen automatically if chk_update_peaks == 1?

**Comment by cpaulgilman** [comment]
> Good catch! In that case, do we want the yes/no dialogue box to pop up, or should the overwrite happen automatically if chk_update_peaks == 1?

I think it can be automatic.

**Review by cpaulgilman — APPROVED** [review]
Looks good now. Thanks!

**Pull request merged**
