### PR TITLE
Fixes SAM#496

### PR DESCRIPTION
**Pull request by sjanzou**

### CODE REVIEW

**Review by brtietz — APPROVED** [review]
I checked out the changes and tested locally and this looks great! Obviously needs to wait for the SSC PR to be ready (see comments there).

**Review by cpaulgilman — COMMENTED** [review]
The total number of cells in now positive, and close to correct, but the value shown for 14 cells and 158,730,160 strings is 2,222,222,336 and, if my calculator is working correctly, I would expect it to be 2,222,222,240.

image

**Comment by sjanzou** [comment]
@cpaulgilman, another fun experiment in rounding... In Excel, multiply 14 by 158730160 and get 2222222240 as your correct calculator showed. Now, take 2222222236 and divide by 158730160 and get 14 in Excel (see attached workbook.
Based on your observation and comments from @brtietz and @dguittet, I suggest we move this issue to Patch 2 or update all constraints to have max integer (2147483647) for Patch 1 as suggested by @dguittet for consistency between UI and all libraries and compute modules in ssc

**Comment by sjanzou** [comment]
Rounding error as reported by Excel: 
[Rounding error.xlsx](https://github.com/NREL/SAM/files/6028062/Rounding.error.xlsx)

**Comment by sjanzou** [comment]
The issue from @cpaulgilman demonstrated in Excel
image

**Comment by sjanzou** [comment]
@cpaulgilman, @brtietz, @dguittet are we good for patch 2 with PR #543 ?

**Comment by brtietz** [comment]
@sjanzou Looks like there's still a failing test in https://github.com/NREL/ssc/pull/541, and I'm not sure the discussion with @dguittet there was fully resolved? Something to discuss during next week's meeting? Or a side meeting?

**Review by cpaulgilman — APPROVED** [review]

**Comment by brtietz** [comment]
Closed as per discussion in 11/16 mtg

**Pull request closed without merging**
