### PR TITLE
Billing demand ratchets for energy charges

### PR DESCRIPTION
**Pull request by brtietz**
SAM side of billing demand for kWh/kW rates. Should be tested alongside SSC PR https://github.com/NREL/ssc/pull/580

A good rate to test with: https://en.openei.org/apps/IURDB/rate/view/5f73585d5457a3dc0b692d6f
Documentation: https://github.com/NREL/SAM-documentation/blob/master/Utility%20Rates/billing_demand_percentages/GPC_PLL_Tiered_Bill_Calc_Example_v4.xlsx

### CODE REVIEW

**Review by mjprilliman — COMMENTED** [review]
Looks good, just need to change the on_load name.  I will wait for Paul's changes before approval.

**Review by cpaulgilman — APPROVED** [review]
I added commits to improve the UI and for new Help topic. These involved adding a new UI variable with defaults and changing the name of a UI form, so hope they don't result in merge issues. 

All looks great! Thanks.

**Comment by sjanzou** [comment]
@brtietz, looks like the CSP behind the meter configurations are failing...
image

**Review by sjanzou — CHANGES_REQUESTED** [review]
Please check the CSP behind the meter failing configurations defaults and update the failing Travis-CI tests.
image

**Comment by cpaulgilman** [comment]
For MSLF / Commercial, I get this:

image

The defaults seem to be set correctly for CSP configurations:

image

**Comment by brtietz** [comment]
Oddly, what's shown in the defaults manager differs from what's in the text files:

image

I'll fix this manually and push the results.

**Comment by sjanzou** [comment]
@brtietz  looks good now. Let me know when you want a beta version.

**Pull request merged**
