### PR TITLE
Add "Allen method" to Subhourly Clipping Correction Option

### LINKED ISSUE #1850: Add details on subhourly clipping loss correction
Two items that could be helpful:
1. Clarify in the UI that the subhourly clipping correction checkbox is for the "Allen method" image
   - this is to avoid confusion with the "Walker method" - I'm not sure of the status of the Walker method in SAM/pysam, but it's been discussed publicly, e.g., https://www.nrel.gov/docs/fy24osti/90054.pdf.

2. Consider adding a reference to [1] in the help docs under "Enable subhourly clipping loss correction" (_note: I'm a co-author on [1], so I have a potential COI with this suggestion..._) 
image

[1] J. O. Allen, R. Dhakal, W. B. Hobbs, and W. Li, “Allen Method for PV Subhourly Clipping Correction,” 2024. [Online]. Available: https://github.com/epri-dev/allen-subhourly-clipping-correction

### PR DESCRIPTION
**Pull request by cpaulgilman**
# Pull Request Template

## Description

* Change check box label in UI
* Revise Help to add references and clarify difference between hourly and subhourly simulations.

**Note** Help revisions for the "Losses" topic will be committed separately before the Fall 2024 release. Please review and comment on following screenshot.

image

Fixes #1850 (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change modifies variables in existing compute modules. Please see [Checking for PySAM Incompatible API Changes](https://github.com/NREL/SAM/wiki/Checking-for-PySAM-Incompatible-API-Changes).

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cpaulgilman** [comment]
> @cpaulgilman is it ok to add to this branch to add a switch between Allen and Walker methods? It would likely be a dropdown with Allen method and Walker method as the text in the dropdown menu.

Yes -- consider radio buttons in case dropdown suggests preference for one option over the other. Also, is there a way to differentiate the methods with a descriptive term instead of the developer's name?

**Comment by mjprilliman** [comment]
> > @cpaulgilman is it ok to add to this branch to add a switch between Allen and Walker methods? It would likely be a dropdown with Allen method and Walker method as the text in the dropdown menu.
> 
> Yes -- consider radio buttons in case dropdown suggests preference for one option over the other. Also, is there a way to differentiate the methods with a descriptive term instead of the developer's name?

@cpaulgilman I would appreciate notes on the wording here. We can provide references to Allen and Walker in the documentation. 

image


Walker method: https://www.nrel.gov/docs/fy20osti/76859.pdf

**Comment by cpaulgilman** [comment]
@mjprilliman Thanks for adding the Walker method. I've redesigned the UI and revised Help:

image

image

**Comment by mjprilliman** [comment]
> @mjprilliman Thanks for adding the Walker method. I've redesigned the UI and revised Help:
> 
> image
> 
> image

Looks great Paul! My only note would be that only the Allen method I would describe as empirical, so I would probably remove that adjective there.

**Comment by cpaulgilman** [comment]
> Looks great Paul! My only note would be that only the Allen method I would describe as empirical, so I would probably remove that adjective there.

Good catch. I'll remove "empirical" from the general description.

**Review by mjprilliman — APPROVED** [review]

**Pull request merged**
