### PR TITLE
GETEM SAM Updates

### PR DESCRIPTION
**Pull request by mjprilliman**
## Description

-Update GETEM performance models to align with latest Excel model results
-Add PPI base year options for cost multipliers
-Add option for selecting Default configurations (for future Supply Curve updates to run from SAM scripting)
-Gringarten fracture model
-Ramey wellbore temperature model
-Option for inputting reservoir results as csv file (not implemented in ssc yet)
-Cost model updates, Installation cost page updates
-Fix UI errors

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change modifies variables in existing compute modules. Please see [Checking for PySAM Incompatible API Changes](https://github.com/NREL/SAM/wiki/Checking-for-PySAM-Incompatible-API-Changes).

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cpaulgilman** [comment]
## Geothermal Resource Page

1. Typo "reservir" in reservoir parameters radio button list.

2. Index labels for reservoir_pressure_change_type should have comma-separated list of options (this list is in addition to the widget's Object Properties):
image

3. Switching from **Enter change in pressure across the reservoir in units of psi-h per 100 lb:** and **Calculate the reservoir pressure change using simple fracture flow (EGS) only** results in two pop-up windows. The first one has a sentence "The enter change in reservoir option is being used currently" that doesn't make sense to me. I think the behavior when you switch to the **User-entered reservoir model** with one pop-up is a good approach for all of the EGS only options.

4. Reservoir model input table first row is not highlighted in color like other rows.

5. Time in seconds for input table is not clear: If that is seconds over the analysis period, it seems like it would be difficult to know what values to use in the Time column.

## Plant and Equipment Page

1. Red text message "Flash plant efficiency calculated internally" should not be red if it is just informational. I would change the label text from red (and blue) to black.

2. Check box **Automatically set to resource temp**: When it is not checked, are you supposed to be able to edit **Plant Design Temperature**?

## Installation Costs

1. I expected the PPA multiplier year to be for a forecast, but see that they range from 1995 to 2022. It is not clear how choosing a different year affects the inputs because the multipliers are not shown anywhere on the page. It is also not clear how to choose a year since the project people are modeling is likely to be built in the future.

2. Why is the number of injection wells zero? I don't see where to set the number of wells. It's also not clear why there are two different drilling costs for the injection well cost curve:
image

3. The function of the **Specified plant cost** inputs and **Calculate**  buttons is a little unclear. May need to disable all of the cost curve inputs to make this more understandable.

4. It's confusing to have the indirect capital costs box under the total installed costs box because the indirect inputs affect the total installed cost.

5. It is unclear where the calculated "Non-fixed Cost" values in the indirect costs box come from or how to change them. Use PV installation cost as an example for this.

6. % of Direct Cost column has too many percentage symbols ("% of Direct Cost" in the column heading is enough).

## Results

1. On Summary page, fix graph titles "Monthly AC Energy in Year 1" and "Annual AC energy in Year 1".

2. Default case has IRR of 38.82, which seems high.

3. There are not very many performance model outputs. Are geothermal researchers interested in model outputs other than system power generated?

**Comment by mjprilliman** [comment]
> ## Geothermal Resource Page
> 1. Typo "reservir" in reservoir parameters radio button list.
-Fixed
> 2. Index labels for reservoir_pressure_change_type should have comma-separated list of options (this list is in addition to the widget's Object Properties):
Fixed (think this is the wrong screenshot?)
>    image
> 3. Switching from **Enter change in pressure across the reservoir in units of psi-h per 100 lb:** and **Calculate the reservoir pressure change using simple fracture flow (EGS) only** results in two pop-up windows. The first one has a sentence "The enter change in reservoir option is being used currently" that doesn't make sense to me. I think the behavior when you switch to the **User-entered reservoir model** with one pop-up is a good approach for all of the EGS only options.
-Fixed
> 4. Reservoir model input table first row is not highlighted in color like other rows.
-Turning off color mapping of matrix until it can be investigated further. 
> 5. Time in seconds for input table is not clear: If that is seconds over the analysis period, it seems like it would be difficult to know what values to use in the Time column.
> 
-Will look at converting to year of analysis period, still unclear what will be most useful to geothermal industry or what the outputs of software such as GEOPHIRES look like
> ## Plant and Equipment Page
> 1. Red text message "Flash plant efficiency calculated internally" should not be red if it is just informational. I would change the label text from red (and blue) to black.
-Fixed
> 2. Check box **Automatically set to resource temp**: When it is not checked, are you supposed to be able to edit **Plant Design Temperature**?
> 
-Updated behavior of checkbox and input in recent commit
> ## Installation Costs
> 1. I expected the PPA multiplier year to be for a forecast, but see that they range from 1995 to 2022. It is not clear how choosing a different year affects the inputs because the multipliers are not shown anywhere on the page. It is also not clear how to choose a year since the project people are modeling is likely to be built in the future.
-Will have to consult with GETEM team as this was just how it was implemented in the GETEM spreadsheet. May make sense to move it to the Plant Capital Cost box for now as that has the most obvious link to the changing PPI?
> 2. Why is the number of injection wells zero? I don't see where to set the number of wells. It's also not clear why there are two different drilling costs for the injection well cost curve:
-Not sure how you got zero injection wells. The total of the production and injection drilling costs is supposed to below the injection costs
>    image
> 3. The function of the **Specified plant cost** inputs and **Calculate**  buttons is a little unclear. May need to disable all of the cost curve inputs to make this more understandable.
-Might have to rework all cost pages in this way in more detail during a patch
> 4. It's confusing to have the indirect capital costs box under the total installed costs box because the indirect inputs affect the total installed cost.
-Reorganized
> 5. It is unclear where the calculated "Non-fixed Cost" values in the indirect costs box come from or how to change them. Use PV installation cost as an example for this.
-Updated by removing extra calculated boxes
> 6. % of Direct Cost column has too many percentage symbols ("% of Direct Cost" in the column heading is enough).
-Fixed
> 
> ## Results
> 1. On Summary page, fix graph titles "Monthly AC Energy in Year 1" and "Annual AC energy in Year 1".
-Fixed monthly, I think Annual is correct
> 2. Default case has IRR of 38.82, which seems high.
-Will look into default case
> 3. There are not very many performance model outputs. Are geothermal researchers interested in model outputs other than system power generated?
-Will have to get more feedback from users to know what outputs to add.

**Comment by mjprilliman** [comment]
@cpaulgilman I will take another look at some of the unaddressed items next week for the revised schedule.

**Comment by cpaulgilman** [comment]
On Geothermal Resource page, sorry about the wrong screenshot. See the "Index Labels" field for the `reservoir_pressure_change_type` variable. It should be a comma-separated copy of the list of the Items from the Object Properties:

image

Otherwise, the Inputs Browser displays an empty list:

image

For example, see the Battery Dispatch Options FOM form:

image

**Comment by cpaulgilman** [comment]
@mjprilliman I think this is good for now (especially if you can fix that radio button list), I'll approve it so you can merge when you are ready.

**Review by cpaulgilman — APPROVED** [review]

**Pull request merged**
