### PR TITLE
Fixes #1574

### LINKED ISSUE #1574: FOM battery automated dispatch broken for hybrids
### Describe the bug

SAM crashes for Hybrid / Single Owner cases with battery automated dispatch.

### To Reproduce

1. Create any Hybrid / Single Owner case.
2. On Battery Dispatch page, choose Automated option.
3. Click **Simulate**.

### PR DESCRIPTION
**Pull request by sjanzou**
Goes with https://github.com/NREL/ssc/pull/1089

### CODE REVIEW

**Comment by brtietz** [comment]
Looks like this is failing due to "No default value found for 'batt_dispatch_auto_can_fuelcellcharge' in external file (PVWatts Wind Battery Hybrid/Single Owner), using internal default" (this may affect more than just this hybrid)

**Comment by brtietz** [comment]
A second callback error in this configuration:

Could not evaluate callback function:Battery Dispatch Automated FOM->on_load
[6]: reference to unassigned variable:show_hide_charge_options
[6]: error: _s
[5]: eval error in statement list

**Comment by mjprilliman** [comment]
> Looks like this is failing due to "No default value found for 'batt_dispatch_auto_can_fuelcellcharge' in external file (PVWatts Wind Battery Hybrid/Single Owner), using internal default" (this may affect more than just this hybrid)

I was working on adding these checkboxes in another branch (https://github.com/NREL/SAM/pull/1566), I can merge that into this branch once done.

**Comment by sjanzou** [comment]
@mjprilliman , the startup dependent vartable was set to fuel cell vartable (2) instead of the battery vartable (3) for the PVWatts-Wind-FuelCell-Battery / Single Owner configuration... please update in your branch as follows:
image

**Comment by mjprilliman** [comment]
Can this be merged? It's need for configs to pass on develop with https://github.com/NREL/ssc/commit/047030c130fcd70650cad6c7e0344457df367eb7.

**Review by brtietz — APPROVED** [review]
Looks good, thank you!

**Comment by brtietz** [comment]
Yes, just merged it

**Pull request merged**
