### PR TITLE
Inverter Temperature Derate based on Pmax

### PR DESCRIPTION
**Pull request by mjprilliman**
-Changed inverter derate table to be based on ratio of max output power to rated power rather than efficiency
-Update Y-axis label to reflect the ratio rather than the percentage
-Update default inverter temperature derate table to reflect more realistic examples (resource provided by Will Hobbs from Southern Company: https://files.sma.de/downloads/Temp-Derating-TI-en-15.pdf)
-Related NREL/ssc#471, closes NREL/ssc#442

### CODE REVIEW

**Comment by mjprilliman** [comment]
@cpaulgilman There will be some documentation changes based on the improvements in this PR most likely.

**Comment by cpaulgilman** [comment]
Thanks for the documentation heads-up.

**Review by cpaulgilman — APPROVED** [review]
UI looks good. Table is a bit tricky to use, but functional enough once you understand how it works. Is there a maximum limit to the number of columns in the table?

**Comment by mjprilliman** [comment]
Right now I think the labels stop after 9 columns (four different temp-slope combos). But the editor allows more columns to be generated without the appropriate columns (just called 10 and 11). Should a max number of columns be enforced and if so how?

**Comment by cpaulgilman** [comment]
I think it's OK not to enforce a maximum -- we can rely on an explanation in Help. Perhaps we could add a UI label with text like "Table supports up to four temperature - slope pairs in each row." either above the table or below it somewhere next to the **Update plot** button.

**Pull request merged**
