### PR TITLE
Update Summary page graphs, timeseries graphs for BTM Battery technologies

### LINKED ISSUE #1871: Implement summary metric and graph updates for battery configs
### Is your feature request related to a problem? Please describe.

-Implement previously discussed battery autograph and summary tables for improved visualizations
-Look at setting stacked area chart with battery / utility rate / load interactions as default

### PR DESCRIPTION
**Pull request by mjprilliman**
## Description

-Add summary graphs showing stack of monthly from battery, grid, system to load
-Add summary graphs showing stack of monthly energy charges, demand tou charges, demand flat charges, and fixed charges
-Add default timeseries graph showing stacked area plot of battery, grid, system to load lifetime timeseries; Battery SOC line graph on right-hand Y-axis
-Remove summary page PV loss graphs for technologies where Loss Diagram already exists
-Requires help documentation update from @cpaulgilman explaining 'Edit view settings and graph scaling' window

image

image

image

Fixes #1871

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] This change requires a documentation update
- [ ] This change modifies variables in existing compute modules. Please see [Checking for PySAM Incompatible API Changes](https://github.com/NREL/SAM/wiki/Checking-for-PySAM-Incompatible-API-Changes).

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by cpaulgilman — APPROVED** [review]
I like it!

My only suggestion is to have the time series graph zoom in to the first 7 days of the year to show one full week.

Help revision:

## Time Series

image

**Review by brtietz — APPROVED** [review]
I like this as well! Especially how the rate components show the energy charges phasing out as the net metering credits build up.

**Comment by mjprilliman** [comment]
> I like it!
> 
> My only suggestion is to have the time series graph zoom in to the first 7 days of the year to show one full week.
> 
> Help revision:
> 
> ## Time Series
> image

@cpaulgilman We had discussed maybe adding a section going over the controls in the toolbar with a screenshot of the dialog, but I think your note here covers it well so I think it is fine as is.

**Comment by cpaulgilman** [comment]
> @cpaulgilman We had discussed maybe adding a section going over the controls in the toolbar with a screenshot of the dialog, but I think your note here covers it well so I think it is fine as is.

I added a section to the Time Series topic in help to describe the options in the View Settings window: 
[results-time-series-view-settings.pdf](https://github.com/user-attachments/files/17546025/results-time-series-view-settings.pdf)

I'm not sure what the **Show sum over time step** option does or that it works at all, so I did not include a description of that option.

**Pull request merged**
