### PR TITLE
UI forms and defaults for battery adjust losses

### PR DESCRIPTION
**Pull request by brtietz**
# Pull Request Template

## Description

Adds UI forms for battery adjust losses. Uses two forms so we can add adjust losses to PVWatts-Battery. Open to other ideas as to how to structure this form.

Pairs with SSC pull request https://github.com/NREL/ssc/pull/1241

Fixes (https://github.com/NREL/SAM/issues/1869)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update
- [ ] This change modifies variables in existing compute modules. Please see [Checking for PySAM Incompatible API Changes](https://github.com/NREL/SAM/wiki/Checking-for-PySAM-Incompatible-API-Changes).

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by cpaulgilman — CHANGES_REQUESTED** [review]
Setting up subhourly battery availability losses with hourly simulation time step should trigger an SSC simulation error (like PV availability losses).

I recommend putting both Battery Ancillary Losses and Battery Availability Losses forms under a single "Battery Losses" collapsible panel. Revised suggestion: Put widget on Battery Model Simple and Battery Model Simple with REopt forms for PVWatts-Battery, and create single Battery Losses form with both ancillary and availability loss inputs.

**Review by cpaulgilman — APPROVED** [review]
UI forms look good now. I made some additional changes (including changing the UI form file name from "Battery Ancillary Losses.json" to "Battery Losses.json").

**Review by cpaulgilman — APPROVED** [review]

**Comment by dguittet** [comment]
@brtietz is there an output for the availability loss that can be viewed in Time series?

**Comment by brtietz** [comment]
> @brtietz is there an output for the availability loss that can be viewed in Time series?

Thanks for the reminder - I just pushed code for "Battery performance loss adjustment" to ssc.

**Comment by brtietz** [comment]
> Not sure if I'm doing this right, but since the time series losses aren't working atm, I tried the period losses and added one hour of 100 loss: image
> 
> This is for manual dispatch: image
> 
> I expected the discharge to go to 0 for an hour but then afterwards dispatch at 100%, but the discharge for the 1st day is 0. In contrast, the 2nd day has the "normal" discharge which lasts for 4 hours. image

The 1st day doesn't discharge because a 100% loss drops the state of charge to zero. Here's the same thing with battery SOC and the new performance adjust loss output:

image

**Comment by dguittet** [comment]
> > @brtietz is there an output for the availability loss that can be viewed in Time series?
> 
> Thanks for the reminder - I just pushed code for "Battery performance loss adjustment" to ssc.

Hmm.. the naming for the input (Battery Availability) is different than that of the output (Battery performance adjustment), which is confusing.

**Comment by brtietz** [comment]
> Hmm.. the naming for the input (Battery Availability) is different than that of the output (Battery performance adjustment), which is confusing. And shouldn't it be listed in the var_table for battery?

Naming is updated as we discussed. Including it in a vartable in common.cpp allows for the same definitions to be used in cmod_battery.cpp, cmod_pvsamv1.cpp, and cmod_battwatts.cpp (the latter wouldn't work if it was in the vartable for battery)

**Comment by cpaulgilman** [comment]
@brtietz 

1. Thank you for adding the Battery availability loss output. 
 
    There is some inconsistency now: 

    * Total AC availability is reported as a single value in %
    * Total DC availability is reported as a single value in %
    * Total battery availability is not reported.
    * Time series AC availability loss is reported in kW
    * Time series DC availability loss is not reported
    * Time series battery availability loss is reported in %
 
    This is probably a separate issue to handle the output consistently across all performance models.

2. I am not seeing a UI callback error about `reopt_size_battery()`, and the REopt API call is working from this branch for both PV-Battery and PVWatts-Battery. I pushed a fix to re-implement some UI changes that didn't get transferred from Develop after I merged my REopt branch.

**Pull request merged**
