### PR TITLE
Geothermal Drilling cost curve updates

### PR DESCRIPTION
**Pull request by mjprilliman**
## Description

-Update drilling and injection cost curves to be based off scenario (4 options), well diameter (2 options), and well type (2 options)
-Add plot showing where along the cost curve scenarios the selection lies
-interface redesign

### CODE REVIEW

**Comment by mjprilliman** [comment]
@cpaulgilman I could use some interface design notes on this

**Comment by cpaulgilman** [comment]
@mjprilliman This is pretty cool. Nice work! I can make  couple of small tweaks to make the layout clearer if you don't mind. 

A couple of questions:

1. Do you have a preference for the "Update Plot" button vs automatically updating it based on on_change events for the cost curve, well type, and well diameter options? It seems like it would be best for the state of the plots to always match the state of the options and calculated dollar amounts. But maybe I'm missing a reason to have the user update the plot manually?

2. This will need documentation. Do you have references with definitions of the baseline, intermediate, and ideal cost curves?

**Comment by mjprilliman** [comment]
> @mjprilliman This is pretty cool. Nice work! I can make couple of small tweaks to make the layout clearer if you don't mind.
> 
> A couple of questions:
> 
> 1. Do you have a preference for the "Update Plot" button vs automatically updating it based on on_change events for the cost curve, well type, and well diameter options? It seems like it would be best for the state of the plots to always match the state of the options and calculated dollar amounts. But maybe I'm missing a reason to have the user update the plot manually?
> 2. This will need documentation. Do you have references with definitions of the baseline, intermediate, and ideal cost curves?

1. I think I like updating for any changes too and I don't see a reason not to so I will update that. 
2. I will get a reference from the people that worked on the curves. 
Also I seemed to have caused a configuration to crash so I will investigate that further. I believe it is coming from Geothermal LCOE or Geothermal None

**Comment by mjprilliman** [comment]
Moved to https://github.com/NREL/SAM/pull/912/files

**Pull request closed without merging**
