### PR TITLE
Fix SAM #1485

### PR DESCRIPTION
**Pull request by sjanzou**

### CODE REVIEW

**Review by cpaulgilman — COMMENTED** [review]
Functionality is good, but Results button requires two clicks to switch to Results page instead of one.

**Comment by sjanzou** [comment]
> Functionality is good, but Results button requires two clicks to switch to Results page instead of one.

I have tested on Windows 11 and RHEL 8.6 and the results button is only requiring one click for me
image

@mjprilliman , @brtietz  - how many clicks is the results button requiring for you to go to the results page from an input page?

**Review by brtietz — APPROVED** [review]
This works for me with one click

**Review by cpaulgilman — APPROVED** [review]
Works on Mac with single click.

**Pull request merged**
