### PR TITLE
Consolidate grid outage inputs on new Grid Outage input page

### LINKED ISSUE #864: Specifying a critical load on stand alone battery produces a callback error
The grid page used by stand alone battery doesn't have the grid outage input, and the resiliency calculations variable is fixed to "calculate resiliency only for outage time steps," so specifying a critical load does not result in any change to the simulation outputs. This is case 5 in the help file.

Additionally, if one attempts to specify a critical load, one gets the error:

Could not evaluate callback function:crit_load_pct->on_change

> [45]: reference to unassigned variable:is_grid_outage
> [45]: error: _s
> [45]: error: _s
> [45]: error: _s
> [44]: eval error in statement list
> [44]: error inside function call
> [19]: eval error in statement list

There are three options to remedy this:

1. Add the grid outage input and enable the resiliency calculations, bringing the code in line with pv-battery and generic battery
2. Fix the resiliency calculations to "calculate for all timesteps" so that specifying a critical load triggers the resiliency runner
3. Disable the inputs for critical load

### LINKED ISSUE #891: Move critical load, grid outage, and minimum battery SOC for grid outage inputs to new page
The inputs used to calculate "resiliency" metrics are on three different input pages for BTM battery configurations, which makes them hard to find.

Solution is to move the inputs to a single new input page. Use these UI forms:

* Electric Load Crit, Electric Load Critical
* Grid Outage
* Battery Dispatch BTM Outage SOC

Need to decide where to show calculated monthly critical load (currently on Load page, which is good for comparing to other load data, but would be on separate page from new input page).

Name for new input page "Grid Outage"?

Note to avoid "resiliency" because its meaning is ambiguous.

Related to https://github.com/NREL/SAM/issues/864 and https://github.com/NREL/SAM/pull/884.

### PR DESCRIPTION
**Pull request by cpaulgilman**
Goes with https://github.com/NREL/ssc/pull/739

Fixes #891 

Fixes #864 by adding Grid Outage page to BTM Standalone configurations.

Revises version upgrade script text added in PR #884

## Tasks

Test all configurations with BTM battery, except PVWatts - Battery

* PV Battery

* Generic Battery

* Fuel Cell

* Standalone Battery

Rename Grid page to Grid Limits page to differentiate from Grid Outage.

* Note that this was Grid Limits before we added grid outage inputs to the page.

Create new Grid Outage page and consolidate inputs on one page.

* Move Grid Outage from old Grid page

* Move Battery Dispatch BTM Outage SOC form from BTM battery page

* Move critical load inputs to new page

Remove LOAD_BELPE_CRIT and LOAD_SIMPLE_CRIT from startup script after testing all configs.

Fix Load page tooltips.

Check that `crit_load_is_shown` is not needed in SSC and remove default input in relevant configs.

```
PV Battery, Residential
PV Battery, Commercial
PV Battery, Third Party
PV Battery, Host Developer
Generic Battery, Residential
Generic Battery, Commercial
Generic Battery, Third Party
Generic Battery, Host Developer
Standalone Battery, Residential
Standalone Battery, Commercial
Standalone Battery, Third Party
Standalone Battery, Host Developer
Fuel Cell, Commercial
```

Check `resiliency_graphs()` autograph function: Keys off of exclusive var that we are no longer using, so check for PV Battery, Generic Battery, Standalone Battery, Fuel Cell config instead.

Modify Electric Load Data form to handle load data with or without critical load data so we don't have to maintain two versions of the form.

Version upgrade script to alert users when opening SAM 2020.11.29 or older files that inputs are on new Grid Outage page. Also change PVWatts message from warning to error.

Add critical load defaults to non-storage BTM configurations to allow for single Electric Load Data form for storage and non-storage configurations. This means adding defaults that are not used to BTM configurations without storage, but perhaps could be useful in future if we add critical load capabilities later.

```
annual_crit
crit_1
crit_2
crit_3
crit_4
crit_5
crit_6
crit_7
crit_8
crit_9
crit_10
crit_11
crit_12
```

Update Help.

Deal with displaying monthly critical load on load page.

* UI text
* Help

Run defaults script to make sure simulations work.

Click through Grid Outage and Electric Load Data UI page in BTM PV Battery, Generic Battery, Standalone Battery, Fuel Cell configs to check for UI callback issues.

## Type of change

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] This change requires a documentation update

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by brtietz** [comment]
Behavior on the fuel cell page is inconsistent. I specified a critical load without enabling the battery, and got the expected warning, but then I'm allowed to modify two variables but not the grid outage:

image

I'd prefer all three boxes below the critical load specification to be greyed out while the battery is disabled, but mostly just looking for consistency.

**Comment by brtietz** [comment]
Another bug with the enable/disable code. Steps to reproduce:

(1) Change to "use time series critical load data"
(2) Specify one or more non-zero hours of critical load
(3) Change back to "calculate critical load as percentage..."
(4) Boxes stay enabled when they should be disabled.
(5) If you specify a grid outage at step (3) or (4), you get the following error when simulating:

> exec fail(battery): If grid_outage is specified in any time step, crit_load must have length > 0 and values > 0
> Simulation battery failed :exec fail(battery): If grid_outage is specified in any time step, crit_load must have length > 0 and values > 0

**Review by brtietz — CHANGES_REQUESTED** [review]
The page looks good, help directs to the right places, and the electric load page suggests scaling factors and similar are still working.

The enable/disable functions need to handle a few more edge cases, plus the defaults issue we discussed over email.

Nice work!

**Comment by dguittet** [comment]
@cpaulgilman I like this organization! However, the PV Battery - Single Owner config has a callback error now:

image

I adjusted the dimensions of a text box a little bit for display on Mac.

**Review by sjanzou — CHANGES_REQUESTED** [review]
@cpaulgilman, same issue as @dguittet reported

Steps to reproduce:
1. Add Case
2. Energy Storage -> Detailed PV-Battery
3. Power Purchase Agreement -> Single Owner
image

Same issue with Detailed PV-Battery / Merchant Plant and all Detailed PV-Battery / Power Purchase Agreement markets

**Comment by cpaulgilman** [comment]
@dguittet, @sjanzou The issue with autographs for FOM PV Battery configs should be fixed after my latest commit. Thanks!

**Review by brtietz — APPROVED** [review]
Latest revision looks good on Windows, thanks!

**Review by dguittet — APPROVED** [review]
Looks great!

**Review by sjanzou — APPROVED** [review]
Working good!

**Pull request merged**
